### ISSUE TITLE
可以搞个树莓派的版本么？

### ISSUE THREAD

**Issue by bymao** [RayWangQvQ/BiliBiliTool#11]
现在的linux-64好像不能在树莓派上执行。最好整个32位的~~

**Comment by RayWangQvQ** [comment]
试下Release里的 linux-arm.zip

**Comment by bymao** [comment]
linux-arm.zip可以！刚才没注意~

**Comment by RayWangQvQ** [comment]
其实是你发了issue之后我补上去的，能用就好，那这个issue我关了哈
