### ISSUE TITLE
可以为自动投币设一个secrets开关吗？还有

### ISSUE THREAD

**Issue by zerokos** [RayWangQvQ/BiliBiliTool#12]
从来不投币的希望设一个secrets开关，能够关闭自动投币的功能，
还有就是给自己充电也希望有个开关，因为每个月的B币券都要拿去买漫画券

**Comment by RayWangQvQ** [comment]
全部都有，见 [配置说明](https://github.com/RayWangQvQ/BiliBiliTool.Docs/blob/main/configuration.md)

**Comment by zerokos** [comment]
> 全部都有，见 [配置说明](https://github.com/RayWangQvQ/BiliBiliTool.Docs/blob/main/configuration.md)

学会了，谢谢大佬
