### ISSUE TITLE
centos8 运行

### ISSUE THREAD

**Issue by stoplove** [RayWangQvQ/BiliBiliTool#144]
![微信截图_20201126161018](https://user-images.githubusercontent.com/47299503/100324263-f34de100-3001-11eb-8421-2c16848b2ffa.png)
这个该怎么办

**Comment by frisktale** [comment]
看错误信息好像是你没有装dotnet 5.0的runtime，在服务器上装一下。

**Comment by jli113** [comment]
下载：
https://dotnet.microsoft.com/download/dotnet-core/3.1
安装：
sudo mkdir -p $HOME/dotnet
sudo tar zxf dotnet-sdk-3.1.100-linux-arm.tar.gz -C $HOME/dotnet
export DOTNET_ROOT=$HOME/dotnet
export PATH=$PATH:$HOME/dotnet
测试安装：
dotnet

**Comment by frisktale** [comment]
你这是net core 3.1的sdk，他这错误信息是说缺5.0的啊。而且看信息，已经装了3.1.7的sdk了

**Comment by hjkl950217** [comment]
亲，解决了的话就把issues关闭了吧，让真正的问题更容易被看到
