### ISSUE TITLE
action 启动异常

### ISSUE THREAD

**Issue by T3rdW** [RayWangQvQ/BiliBiliTool#158]
![image](https://user-images.githubusercontent.com/14792476/100495546-a4ca4f00-3187-11eb-8d6f-15d425804674.png)
不知道是什么问题,前2天运行正常

**Comment by zlq4863947** [comment]
同样的错误

**Comment by Dreamyangli** [comment]
我的也是这样

**Comment by nebulaeos** [comment]
前两天允许正常，今天执行出现同样的错误

**Comment by Gineia** [comment]
一样的问题，正常跑了一周后出这个

**Comment by bigxiongxu** [comment]
之前用安装版的  也出过这个问题  现在在这也出现了

**Comment by LY134651** [comment]
134加一 配置了au

**Comment by LY134651** [comment]
也一样 配置了ua

**Comment by hjkl950217** [comment]
412 应该是cookie过期了

**Comment by LY134651** [comment]
> 412 应该是cookie过期了

刚更新的 一会412 一会134

**Comment by hjkl950217** [comment]
这个就很迷了。。我才配置了这个库 能跑。 会不会是天天运行被B站风控了

**Comment by LY134651** [comment]
> 这个就很迷了。。我才配置了这个库 能跑。 会不会是天天运行被B站风控了

跑可以跑，就是会失败 过会没准就成功了 很迷

**Comment by Gineia** [comment]
今天又遇到了，马上换新的SESSDATA和BILIJCT再次运行还是失败。过了几分钟没再次修改，只重启了一下就不报错了，可能是b站后台刷新参数机制的问题

**Comment by T3rdW** [comment]
大部分应该是cookie过期问题.

**Comment by drw2005** [comment]
早上还正常运行，刚刚中午2点左右推送到微信又提示412错误了。。。

**Comment by RayWangQvQ** [comment]
与 #61 重复
