### ISSUE TITLE
会被封号吗？

### ISSUE THREAD

**Issue by zhhl9101** [RayWangQvQ/BiliBiliTool#165]

**Comment by hjkl950217** [comment]
应该不会，这个是合理的领取自己的东西，不是去疯狂刷什么的

**Comment by Misaka-hly** [comment]
## 不会 
<p>只是调用api而已，相当于自己操作，不会的。</p>

**Comment by ati9527** [comment]
![image](https://user-images.githubusercontent.com/55564669/100722117-37265900-33fb-11eb-99c3-d7951fff3a7f.png)
今天收到这么个通知

**Comment by drw2005** [comment]
有可能，今天也收到警告了。

**Comment by hjkl950217** [comment]
应该是检测到请求IP是从外面来(不是常驻IP)，我今天也由到了。
准备空了做成docker镜像，在自己的电脑上面定时运行吧

**Comment by u-mie** [comment]
可以做成路由插件吗

**Comment by msn1983aa** [comment]
> 可以做成路由插件吗

可以做的，京东签到的action脚本也做成了op的ipk插件，就看有没有大神做了
