### ISSUE TITLE
希望消息推送支持api

### ISSUE THREAD

**Issue by Mmx233** [RayWangQvQ/BiliBiliTool#17]
个人不是很喜欢用微信，希望能支持推送json信息到后端api地址，可以实现更舒适的推送，自由统计和扩展。

**Comment by LittleNightmare** [comment]
嗯，我个人是有QQ机器人的，使用别的有些多此一举

**Comment by RayWangQvQ** [comment]
v1.1.0新增了一些推送端：
![image](https://user-images.githubusercontent.com/31154238/103327873-6cbd7100-4a91-11eb-87dd-62ff9cade34b.png)

下个版本会尝试添加一个自定义端，用来往自定义的Api推送。

**Comment by RayWangQvQ** [comment]
本来在1.1.0的时候就想加的，但是鉴于自定义的api太过灵活，想只通过配置兼容各种自定义的请求规范很麻烦。
不说自定义的推送api，就是前面提到的tg、企业微信、钉钉等官方提供的api规范都彼此有很大差异。

目前的想法是，可以将api的url地址作为配置，然后再放一个用来当作body的json字符串作为配置，可以在这个json中适配自己api的字段规范，留个占位符用来替换日志内容。

如果想要再进一步自定义日志的样式、内容啥的，可能性价比最高的方式还是自己去扩展代码，加一个日志输出端了：
![image](https://user-images.githubusercontent.com/31154238/103328601-6b417800-4a94-11eb-9fcd-dccac3665aa4.png)

**Comment by LittleNightmare** [comment]
> 本来在1.1.0的时候就想加的，但是鉴于自定义的api太过灵活，想只通过配置兼容各种自定义的请求规范很麻烦。
> 不说自定义的推送api，就是前面提到的tg、企业微信、钉钉等官方提供的api规范都彼此有很大差异。
> 
> 目前的想法是，可以将api的url地址作为配置，然后再放一个用来当作body的json字符串作为配置，可以在这个json中适配自己api的字段规范，留个占位符用来替换日志内容。
> 
> 如果想要再进一步自定义日志的样式、内容啥的，可能性价比最高的方式还是自己去扩展代码，加一个日志输出端了：
> ![image](https://user-images.githubusercontent.com/31154238/103328601-6b417800-4a94-11eb-9fcd-dccac3665aa4.png)
我觉得很合理，给个api的url口，和json的位置就好

**Comment by RayWangQvQ** [comment]
当前版本（v1.1.1）已完成开发，详情可以参考配置说明文档
![image](https://user-images.githubusercontent.com/31154238/103397657-3efd2880-4b74-11eb-97af-34262f76c9c4.png)
