### ISSUE TITLE
最近的412可能的原因

### ISSUE THREAD

**Issue by 1Silencer** [RayWangQvQ/BiliBiliTool#189]
![image](https://user-images.githubusercontent.com/44016268/100559975-559f2e00-32ef-11eb-996b-2443e9c62b4a.png)

**Comment by 1Silencer** [comment]
如果使用多线程、多进程或者并发等在同一时间点请求多次的方法,可能会触发b站风控策路,返回的状态码是412
看能不能设定每次action的时间间隔，工作流内的请求也可以适当延缓

**Comment by RayWangQvQ** [comment]
谢谢提醒，但是代码里我没有使用多线程。
最新进展我贴到 #61 了，升级v1.0.13目前应该能解决412问题，有待进一步观察。
因为重复，这条就先关了。
