### ISSUE TITLE
RUN APP时报错

### ISSUE THREAD

**Issue by LiJunYi2** [RayWangQvQ/BiliBiliTool#208]
![11](https://user-images.githubusercontent.com/40384503/100590864-eac21700-332f-11eb-83cb-1ffe938cc479.png)

**Comment by ZSX-JOJO** [comment]
拉取最新的
再试一下,人家作者更新了.我试了现在正常了.

**Comment by Weidows** [comment]
之前遇到过类似的问题,我的是因为浏览器清理垃圾把B站cookie清掉了,需要重新配置secret

**Comment by RayWangQvQ** [comment]
与 #61 重复
