### ISSUE TITLE
Server酱通知失效

### ISSUE THREAD

**Issue by Weidows** [RayWangQvQ/BiliBiliTool#224]
- 按照文档配置好了secret,action运行正常
- 查看log也没出错,但是接收不到Server酱微信通知.

**Comment by TinQlo** [comment]
发现你的server酱key的地方是空值，key要先去他们家网站申请一下

**Comment by hjkl950217** [comment]
同上。。

作者的教程:https://hub.fastgit.org/RayWangQvQ/BiliBiliTool.Docs/blob/main/configuration.md

你注册好后登录，在这里:
![image](https://user-images.githubusercontent.com/11371470/100857422-a23d6180-34c7-11eb-9995-5aefada1a76d.png)


然后中按这样设置:
![image](https://user-images.githubusercontent.com/11371470/100857362-9356af00-34c7-11eb-8e3a-868d837416a4.png)

**Comment by hjkl950217** [comment]
亲，要是解决了就把issues关了吧，让真正的问题更容易被看到
