### ISSUE TITLE
centos系统报错The SSL connection could not be established

### ISSUE THREAD

**Issue by lvmaozilinke** [RayWangQvQ/BiliBiliTool#23]
初学者刚买了个服务器，想在服务器上运行，怎样运行这个Ray.BiliBiliTool.Console文件呢？

**Comment by Mmxp** [comment]
Linux运行比较玄学，我在一台香港和一台杭州的centos系统服务器上使用，会出现无法请求ssl的情况。Centos系统里，预编译版和使用dotnet环境直接运行源码的结果一样出错。
用本地的Ubuntu运行能够使用。GitHub的action也是Ubuntu……

**Comment by RayWangQvQ** [comment]
linux的Release包有两个版本：64位版和arm版。
是两个版本都试过都有问题吗？

**Comment by lvmaozilinke** [comment]
正在尝试更换为Ubuntu，主要是不知道在linux服务器下怎么运行Ray.BiliBiliTool.Console这个程序，我刚学习linux，想把这个利用宝塔的计划运行让他每天自动运行，宝塔支持shell脚本，我查阅了文档和教程，没看懂，有能在linux下运行的可以说一下指令代码吗？

**Comment by RayWangQvQ** [comment]
难道不是直接使用命令运行包里的Ray.BiliBiliTool.Console就行了吗？
非Window环境我也不是很了解，楼上有位大佬，你可以问问他 @Mmxp

**Comment by Mmxp** [comment]
> linux的Release包有两个版本：64位版和arm版。
> 是两个版本都试过都有问题吗？

试了amd我就去试环境+源码了。

**Comment by Mmxp** [comment]
> 正在尝试更换为Ubuntu，主要是不知道在linux服务器下怎么运行Ray.BiliBiliTool.Console这个程序，我刚学习linux，想把这个利用宝塔的计划运行让他每天自动运行，宝塔支持shell脚本，我查阅了文档和教程，没看懂，有能在linux下运行的可以说一下指令代码吗？

ssh，进目录然后./Ray.BiliBiliTool.Console就行，建议挂screen里

**Comment by Mmxp** [comment]
![image](https://user-images.githubusercontent.com/36563672/98788253-923be000-243b-11eb-91a0-ef9cf32d0238.png)
ARM直接无法运行

**Comment by lvmaozilinke** [comment]
> > 正在尝试更换为Ubuntu，主要是不知道在linux服务器下怎么运行Ray.BiliBiliTool.Console这个程序，我刚学习linux，想把这个利用宝塔的计划运行让他每天自动运行，宝塔支持shell脚本，我查阅了文档和教程，没看懂，有能在linux下运行的可以说一下指令代码吗？
> 
> ssh，进目录然后./Ray.BiliBiliTool.Console就行，建议挂screen里

我今晚试试

**Comment by lvmaozilinke** [comment]
> ![image](https://user-images.githubusercontent.com/36563672/98788253-923be000-243b-11eb-91a0-ef9cf32d0238.png)
> ARM版直接无法运行

我的是64的

**Comment by lvmaozilinke** [comment]
> 难道不是直接使用命令运行包里的Ray.BiliBiliTool.Console就行了吗？
> 非Window环境我也不是很了解，楼上有位大佬，你可以问问他 @Mmxp

楼下给出解答了，我没有验证，今晚上验证一下

**Comment by RayWangQvQ** [comment]
> Linux运行比较玄学，我在一台香港和一台杭州的centos系统服务器上使用，会出现无法请求ssl的报错（One or more errors occurred. (The SSL connection could not be established, s……）。Centos系统里，预编译版和使用dotnet环境直接运行源码的结果一样出错。
> 用本地的Ubuntu运行能够使用。GitHub的action也是Ubuntu……

我怀疑不是Centos和Ubuntu的问题，是服务器环境和本地环境的问题。
有没有人在本地使用Centos运行成功的，可能来说下。
如果本地能成功，那可能是服务器的网络问题，是不是只允许https不允许http？

**Comment by RayWangQvQ** [comment]
[微信讨论群](https://github.com/RayWangQvQ/BiliBiliTool/issues/27)

**Comment by lvmaozilinke** [comment]
> ![image](https://user-images.githubusercontent.com/36563672/98788253-923be000-243b-11eb-91a0-ef9cf32d0238.png)
> ARM版直接无法运行

@Mmxp 
同样不能运行，我试试用GitHub Secrets吧
<img width="614" alt="不能运行1" src="https://user-images.githubusercontent.com/53802281/98805600-ccfd4280-2452-11eb-8309-c36278c1dfdf.PNG">

**Comment by lvmaozilinke** [comment]
> ![image](https://user-images.githubusercontent.com/36563672/98788253-923be000-243b-11eb-91a0-ef9cf32d0238.png)
> ARM版直接无法运行
@Mmxp 
![Uploading 成功1.PNG…]()

成功了，我刚才重新把文件上传到了服务器，重新运行了一下成功了 #

**Comment by RayWangQvQ** [comment]
> Linux运行比较玄学，我在一台香港和一台杭州的centos系统服务器上使用，会出现无法请求ssl的报错（One or more errors occurred. (The SSL connection could not be established, s……）。Centos系统里，预编译版和使用dotnet环境直接运行源码的结果一样出错。
> 用本地的Ubuntu运行能够使用。GitHub的action也是Ubuntu……

群里有朋友解决了，参见 [https://github.com/RayWangQvQ/BiliBiliTool/issues/46](https://github.com/RayWangQvQ/BiliBiliTool/issues/46)
