### ISSUE TITLE
[建议] 更改默认为自己充电的日期

### ISSUE THREAD

**Issue by EdisonJwa** [RayWangQvQ/BiliBiliTool#24]
更改默认为自己充电的日期

```
--- 开始【每月为自己充电】---
目标充电日期为 30 号，今天是 11 号，跳过充电任务
---【每月为自己充电】结束 ---
```

原因： 2月份没有30日

**Comment by RayWangQvQ** [comment]
谢谢提供建议，但是这个不会有问题的。
因为默认不是30号，是每个月实际的最后一天，根据实际情况会自动变的，详情可参考配置说明文档。

**Comment by EdisonJwa** [comment]
OK 只是刚刚看到log 
另，是否可以添加推送至 telegram 的支持呢

**Comment by EdisonJwa** [comment]
> OK 只是刚刚看到 log
> 另，是否可以添加推送至 telegram 的支持呢

刚打算再写另一个issue来着

**Comment by RayWangQvQ** [comment]
添加推送至 telegram 需求同 #17
