### ISSUE TITLE
登录异常：B币券data.wallet.coupon_balance含小数，转换为int失败

### ISSUE THREAD

**Issue by Kirietoan** [RayWangQvQ/BiliBiliTool#25]
以下是日志：
Run dotnet run -p ./src/Ray.BiliBiliTool.Console -userId=${userId} -sessData=${sessData} -biliJct=${biliJct} -closeConsoleWhenEnd=1 ${otherConfigs}
[16:22:57 INF] -----开始每日任务-----

[16:22:57 INF] ---开始【登录】---
[16:22:58 FTL] 程序发生异常：One or more errors occurred. (The JSON value could not be converted to System.Int32. Path: $.data.wallet.coupon_balance | LineNumber: 0 | BytePositionInLine: 790.)

**Comment by RayWangQvQ** [comment]
艹难道B币券也会有小数？？？

朋友可以问下你的B币券是多少吗：

![image](https://user-images.githubusercontent.com/31154238/98789942-f8296700-243d-11eb-9a0d-8f3aeae1868c.png)

**Comment by Kirietoan** [comment]
> 艹难道B币券也会有小数？？？
> 
> 朋友可以问下你的B币券是多少吗：
> 
> ![image](https://user-images.githubusercontent.com/31154238/98789942-f8296700-243d-11eb-9a0d-8f3aeae1868c.png)

哈哈哈哈 2.5 之前买了电影看

**Comment by Kirietoan** [comment]
![YSWP(%J_}NHNHRVK_FM1XIS](https://user-images.githubusercontent.com/42679669/98790306-7ab22680-243e-11eb-97a5-9a8d5e825811.png)

**Comment by RayWangQvQ** [comment]
那确认是bug了。
之前硬币出现过小数的bug，解决了，但我天真的认为B币券不能有小数，当时就没改。。。
抱歉，今天晚上发版修复。

**Comment by Kirietoan** [comment]
> 那确认是bug了。
> 之前硬币出现过小数的bug，解决了，但我天真的认为B币券不能有小数，当时就没改。。。
> 抱歉，今天晚上发版修复。

好的 我以为是我哪里配置错了 
今晚重新fork了
谢谢

**Comment by RayWangQvQ** [comment]
没配错，我的错😔。。。
建议Pull Request就行了，不用重新Fork，不然Secrets要重新配了。

**Comment by Kirietoan** [comment]
> 没配错，我的错😔。。。
> 建议Pull Request就行了，不用重新Fork，不然Secrets要重新配了。

好的 谢谢
还请小心 不要被滥用了 就比如前天才被封的那个京东签到的脚本

**Comment by RayWangQvQ** [comment]
被封了？看来有必要建个群方便大家聊聊

**Comment by RayWangQvQ** [comment]
[微信群](https://github.com/RayWangQvQ/BiliBiliTool/issues/27)

**Comment by RayWangQvQ** [comment]
已于当前版本（1.0.8）解决。
