### ISSUE TITLE
关于412错误

### ISSUE THREAD

**Issue by dentycqy** [RayWangQvQ/BiliBiliTool#252]
本地window环境运行,修改appsettings的用户参数后,仍登录报412
最后一行 
 //运行结束后是否立即关闭
  "CloseConsoleWhenEnd": "0" //此处修改为1后运行成功
不知具体是什么问题

**Comment by JunzhouLiu** [comment]
cookies的最后一个参数构造str的时候加个分号`;`就能解决412问题了。

**Comment by RayWangQvQ** [comment]
> cookies的最后一个参数构造str的时候加个分号`;`就能解决412问题了。

彼此之间加个空格也行，调换拼接的先后顺序也行。。。
然后，昨天是删掉一个referer头部立马好了。。。
再然后，有人什么都不改，多运行几次，一样是几率性可以成功。。。
