### ISSUE TITLE
作者：我新建了一个微信反馈群，用来提问和讨论（当然闲聊也行~），issues里尽量只提bug和需求，谢谢

### ISSUE THREAD

**Issue by RayWangQvQ** [RayWangQvQ/BiliBiliTool#27]
![image](https://user-images.githubusercontent.com/31154238/103175138-b431da80-48a2-11eb-9f47-6ff275149fb7.png)

issue我回复的比较慢，有些使用和配置上的问题，其实大家讨论下反而能更高效的解决，而且这么多issue提上来我以为全部都是bug，看的我心慌。

后面如果有bug修复或版本更新，我也会在群里通知的，欢迎需要的朋友进群闲聊~

**Comment by 13467966269** [comment]
我的运行不了。。。cookie也没错。。。

**Comment by RayWangQvQ** [comment]
> 我的运行不了。。。cookie也没错。。。

群里很多热心大佬为你解答~

**Comment by Twenty-slips** [comment]
失效了，大佬

**Comment by RayWangQvQ** [comment]
> 失效了，大佬

好了

**Comment by xcgjack** [comment]
![12D821B7-09A0-4919-A521-EFECE86758AC](https://user-images.githubusercontent.com/35762656/99882847-4a4c6280-2c5e-11eb-93b9-d50238f7a37d.png)
最后这个投币失败不知道为啥

**Comment by wujunze** [comment]
666 亲测好用 很棒

**Comment by lxl19980915** [comment]
失效了大佬

**Comment by RayWangQvQ** [comment]
> 失效了大佬

再试下

**Comment by vip-lp** [comment]
Mir, I'm so sorry that I got a issue when  ran it in Internet! I want your help!
原谅我装一下懂英语，其实就是想遇到两个错误进群向大佬们讨教！感激不尽！
不知道咋了无法加载图片……

#
Duplicate of 
![WGUWTYC0X`O{_7_MI U5GKK](https://user-images.githubusercontent.com/68989992/100542540-82b6f680-3285-11eb-88f9-11ca814aa41a.png)
#

**Comment by manlongdan** [comment]
开启定时同步，同步成功，同步默认关闭，我裂开了

**Comment by vip-lp** [comment]
需要邀请A……

**Comment by nkh0472** [comment]
群满了

**Comment by RayWangQvQ** [comment]
> 开启定时同步，同步成功，同步默认关闭，我裂开了

艹，这好像是个悖论。。。
怎么才能默认关闭，又不会导致开启同步后被重置呢？

**Comment by Kexueguaixiong** [comment]
二维码失效了啊大佬

**Comment by VICTORLLi** [comment]
老哥二维码

**Comment by VICTORLLi** [comment]
用了您的工具好久了，最近不能用了，好心急，大佬加油!

**Comment by Holrissen** [comment]
人数超200了，想进群啊大佬

**Comment by BeiChuang518** [comment]
> 人数超200了，想进群啊大佬

+1

**Comment by gaohan-cmd** [comment]
最近登录都失败哈，是有什么问题了嘛

**Comment by xcsyy** [comment]
群超过200人了

**Comment by qimiaoliaoss** [comment]
> 人数超200了，想进群啊大佬

+1

**Comment by drw2005** [comment]
群二维码失效啦！！！

**Comment by BillScott1024** [comment]
求个新的群二维码

**Comment by myRecycler** [comment]
**[09:11:51 WRN] UserId：*** 不能转换为long型，请确认配置的是正确的Cookie值**
@RayWangQvQ 我配的就是cookies里头的UserId，没问题，求解惑！

**Comment by yunc2500** [comment]
同，求个新的二维码

**Comment by LucasSu520** [comment]
求个新的进群方式

**Comment by Lemon109** [comment]
老哥，二维码失效了

**Comment by zunwenzhe** [comment]
求个新的进群方式

**Comment by seu-wll** [comment]
求一个新的二维码

**Comment by iamvicliu** [comment]
已过期，等新二维码

**Comment by aikunzhe** [comment]
已过期，等新二维码

**Comment by RayWangQvQ** [comment]
更新了

**Comment by qwe123456-1** [comment]
超过200人了

**Comment by zhyy90** [comment]
钉钉推送怎么设置啊，我下载下来本机运行可以，但是github不知道怎么配置

**Comment by Huli-fox** [comment]
> 更新了

超过200人，只可通过邀请进群

**Comment by Lemon109** [comment]
怎么加群啊

**Comment by Lemon109** [comment]
Eternal2z
我微信号

**Comment by DeeDarrick** [comment]
![image](https://user-images.githubusercontent.com/37402795/103538656-97fcf180-4ed1-11eb-88b0-854e1d1235aa.png)
无法运行 ，入群

**Comment by RayWangQvQ** [comment]
二维码已更新（目前并不打算维护多个群，所以满200人之后就不更新二维码了，如果有人退出导致不满200人，也会来更新二维码）。

另外，@199863nothing 和 @Mreblack 两位朋友通过赞赏码赞赏后留言了微信号，我已经试着加你们了，但是我添加的时候显示微信号不存在，不知道是不是备注错了。

之前凡备注里的微信号能搜到的，我都手动加上了。对于赞赏了但是我没能搜到微信号的，没加上抱歉了，感谢你们的赞赏！

**Comment by jing5460** [comment]
@jing207  微信号 请求添加

**Comment by currlan** [comment]
一直显示COOKIES异常。。。。

**Comment by Pedro-18** [comment]
谢谢大佬，想入群，微信号：Pedro_wwy

**Comment by Lemon109** [comment]
谢谢大佬，想入群，微信号：Eternal2z

**Comment by 1012598167** [comment]
谢谢大佬，想入群，微信号：mathslaughterer

**Comment by DollyDino9** [comment]
谢谢大佬，想入群，微信号：Super-Xman00

**Comment by 1012598167** [comment]
无法运行 求入群 #183
![image](https://user-images.githubusercontent.com/40982544/106096033-be7c1880-616f-11eb-8cae-e077c6f6335a.png)
已参考#183 #9 但没用

**Comment by gouda1a1** [comment]
我也是遇到这个问题   二维码  失效了

**Comment by gouda1a1** [comment]
A_grass-roots  谢谢大佬  想入群

**Comment by RayWangQvQ** [comment]
人数比我预想的要多，所以新增了②群，码在1楼，需要的朋友可以进来吹水

**Comment by laopanmemz** [comment]
> 人数比我预想的要多，所以新增了②群（[链接](https://images.cnblogs.com/cnblogs_com/RayWang/1874052/o_210203075103bilibilitool%E2%91%A1%E7%BE%A4%E7%A0%81.png)），码在1楼，需要的朋友可以进来吹水

链接挂了，pr86139083@126.com发下，不过有QQ群吗

**Comment by seiuneko** [comment]
为什么不建个 Telegram 群呢？

**Comment by pytwj** [comment]
二群二维码过期了

**Comment by Empty-city-star** [comment]
二群二维码过期了

**Comment by a747823727** [comment]
过期了

**Comment by keep-reoyf** [comment]
过期了，哈哈哈，差了一天

**Comment by wenmin92** [comment]
微信 wenmin92, 需要进群的可加我，拉你

**Comment by ChenniemuCN** [comment]
同cookie有问题，value值是LIVE_BUVID开头的 是不是这个的原因
[13:56:24 INF] ---开始【登录】---
[13:57:25 WRN] 登录异常，请检查Cookie是否错误或过期
[13:57:25 ERR] 程序发生异常：登录失败，请检查Cookie
[13:57:25 ERR] 程序异常终止，原因：登录失败，请检查Cookie
[13:57:25 INF] 开始推送
[13:57:25 INF] 正在自动关闭应用...
[13:57:25 FTL] Host terminated unexpectedly!
System.Exception: 登录失败，请检查Cookie

**Comment by clown789** [comment]
求拉下群，运行不了

**Comment by HqmJoker** [comment]
大佬们，docker compose报错起不来怎么弄啊？救救孩子吧！！！

**Comment by HqmJoker** [comment]
大佬们，docker compose报错起不来怎么弄啊？救救孩子吧！！！
![1620272156(1)](https://user-images.githubusercontent.com/44420292/117238511-97646f80-ae5f-11eb-82a9-bdc3bacb26fe.png)
![1620272156](https://user-images.githubusercontent.com/44420292/117238513-992e3300-ae5f-11eb-84af-75ca9b71ba53.png)
