### ISSUE TITLE
登录程序发生异常  process completed with exit code 134

### ISSUE THREAD

**Issue by tallmountain2** [RayWangQvQ/BiliBiliTool#270]
11.30左右就github开始邮件提醒  日志显示code134/unbutu最新工作流程参见unbutu-20.04  
代码附上   
[21:45:58 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
Unhandled exception. System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)
 ---> Refit.ApiException: Response status code does not indicate success: 412 (Precondition Failed).
Error: Process completed with exit code 134.

**Comment by RayWangQvQ** [comment]
#27
