### ISSUE TITLE
[建议] 新增为他人充电功能（v1.1.1已完成，升级的朋友请看过来~）

### ISSUE THREAD

**Issue by NAXG** [RayWangQvQ/BiliBiliTool#28]
想给一个关注的妹子自动充电..

**Comment by RayWangQvQ** [comment]
建议已采纳，下个版本（v1.1.1）会提供配置

**Comment by RayWangQvQ** [comment]
v1.1.1已发布，配置方法可参考 [配置说明文档](https://github.com/RayWangQvQ/BiliBiliTool.Docs/blob/main/configuration.md)：

![image](https://user-images.githubusercontent.com/31154238/103390465-7efde480-4b4f-11eb-9ccb-36784efa9395.png)

注意：
默认值是作者（我本人）的UpId，如果想要给自己指定的Up充电，请配置为目标Up的Id；如果确认自己已经认证了创作者身份（没有认证的话无法为自己充电），可以配置为-1为自己充电。

默认值设置成我自己的UpId，有两点考量，
* 第一是有很多人是大会员但不是创作者，导致每月赠送的B币券送不出过期浪费掉
* 第二当然是我个人的一点小私心，希望大家可以体谅

如果有自己的充电计划，可以直接修改掉配置，为自己充、为他人充都可以；
如果不是创作者又没有啥想支持的Up主，也可以就保持配置为我的UpId，个人维护开源不易，感谢支持~

**Comment by 983562336** [comment]
ok

**Comment by NAXG** [comment]
充电成功，感谢.

**Comment by Co2333** [comment]
总感觉这次的412和这个feature有千丝万缕的关系 🥇

**Comment by NAXG** [comment]
先停掉功能测试一下.
