### ISSUE TITLE
【讨论】Github自动发布脚本

### ISSUE THREAD

**Issue by hjkl950217** [RayWangQvQ/BiliBiliTool#291]
看了一下[发布脚本](https://github.com/RayWangQvQ/BiliBiliTool/blob/main/.github/workflows/publish-release.yml)，可以实现自动发布github release信息。有2个问题请教一下:

1.  他是如何获得提交信息的？在`Create release info`脚本中没有看到
2.  像dev分支提了许多，合并到main分支的时候再运行这个脚本，能不能把差异的提交信息也自动获取到？

**Comment by RayWangQvQ** [comment]
1.其实它没有获取提交信息，发布release每次都是我手动触发的（workflow_dispatch）。
这么做不是很合流程，推荐做法是在on事件里检测tag事件，在发现打了tag之后就自动执行打包发布release。
但是之前我在测试脚本的时候，发现获取到的tag前面还有其他很奇怪的文本，就暂时先用手动触发了。

2.这个没有想过，有机会可以一起讨论下。

**Comment by hjkl950217** [comment]
1. 任务是手动触发的，但是没有看到获取文本信息的地方。 我看了一眼github release页面，发现都是有文字的。 所以很好奇那个文本信息是从那里拿到的。

2.  看到一些大的库，他们是有节奏的发布版本。 然后发布信息里就有解决了那些issuse这种，所以在想是不是有自动一点的方法，还是他们手动去写的

**Comment by RayWangQvQ** [comment]
标题和附件是自动生成的，文本是在发布release成功之后，我编辑的。

**Comment by hjkl950217** [comment]
酱紫。。脚本时都看到打包的了
