### ISSUE TITLE
关于优化配置文件读取流程的建议

### ISSUE THREAD

**Issue by nkh0472** [RayWangQvQ/BiliBiliTool#296]
目前的配置文件为`appsettings.json`，每次发布版本更新，安装包里都会自带默认的同名配置文件。而这会导致发布新版本时的一些潜在问题，比如：

- 本地更新时需要覆盖配置文件外的所有文件，很容易手滑

- 不便于在自建服务器上更新

因此，建议自带配置文件不要与实际配置文件重名，以解决覆盖的问题。关于这点，我有几种思路：

- 程序自带配置模板`appsettings.default.json`；用户使用时需要将模板重命名为`appsettings.json`并加以修改。读取配置的流程为先读取`appsettings.default.json`，再读取`appsettings.json`，同项目的内容后者覆盖前者。

- 程序不自带配置文件，首次运行自动生成模板。

- 程序不自带配置文件，而新增一个简单的配置文件生成工具，功能为引导用户填入所需配置。

**Comment by RayWangQvQ** [comment]
已经有朋友提供了PR，实现了根据环境读取相应配置文件的功能（https://github.com/RayWangQvQ/BiliBiliTool/pull/212）。
我已将该PR合并到了当前版本（v1.0.15）中，你可以看下最新版本能否解决你的问题。

**Comment by nkh0472** [comment]
这个功能可以解决一部分问题，不过我期望的是用户直接解压安装包覆盖更新可以不覆盖掉之前填写的配置。
基于你提到的实现，要做的这个还需要修改环境变量，是一个比较麻烦的办法。
这样的话或许还把这一步写进User Guide里才能让用户覆盖更新……

**Comment by hjkl950217** [comment]
@nkh0472 是我提的PR，环境变量配置在电脑里就可以拉。现在主要是github action和docker在跑，本地直接跑的比较少，就没有在这个上面优化。
你的建议里里1个就是这样的，.net core默认就是读取`appsettings.json`,其它的都是通过环境去加载。所以你自己复制一个配置文件，仅保留你要修改的部分即可。
