### ISSUE TITLE
Process completed with exit code 134.

### ISSUE THREAD

**Issue by lvlvlvlvlvlv** [RayWangQvQ/BiliBiliTool#3]
没执行成功，是因为我已经签到过了的原因吗

**Comment by RayWangQvQ** [comment]
![image](https://user-images.githubusercontent.com/31154238/97829727-de817480-1d05-11eb-95c9-35d289bf0347.png)

日志显示登录失败了，建议检查下Cookie是不是配置的不对

**Comment by hikae** [comment]
@RayWangQvQ 您好，我这里返回的数值data.money是有小数的情况，把UseInfo.Money改成了decimal类型就正常了。
![Uploading Snipaste_2020-11-03_10-24-31.png…]()

**Comment by RayWangQvQ** [comment]
@hikae  棒啊！谢谢反馈。硬币竟然可以有小数的...之前我以为只能整数取、整数用...

去B站查了下，发现有条规则：观众投币的百分之十将作为UP主的硬币收入奖励。
猜测应该是这个百分之十导致有小数的吧。

另外，因为我本人的账号没法重现，再请教下，这种有小数的情况，是不是除了登录接口外，获取硬币余额的接口也会报异常？

**Comment by hikae** [comment]
> @hikae 棒啊！谢谢反馈。硬币竟然可以有小数的...之前我以为只能整数取、整数用...
> 
> 去B站查了下，发现有条规则：观众投币的百分之十将作为UP主的硬币收入奖励。
> 猜测应该是这个百分之十导致有小数的吧。
> 
> 另外，因为我本人的账号没法重现，再请教下，这种有小数的情况，是不是除了登录接口外，获取硬币余额的接口也会报异常？

我这里复现的结果是获取硬币余额的时候也会报异常，跟硬币有关的投币、银瓜子兑换硬币这些操作都会显示失败。

**Comment by RayWangQvQ** [comment]
@lvlvlvlvlvlv @hikae 已于当前最新版本(V1.0.2)修复该bug。

**Comment by hikae** [comment]
> @lvlvlvlvlvlv @hikae 已于当前最新版本(V1.0.2)修复该bug。

@RayWangQvQ 我这里测试已经没有问题了！

**Comment by JunzhouLiu** [comment]
有的api返回的值类型可能不一样，比如主站查询硬币余额的一个借口 余额可能会返回一个null ，个人信息的查询接口，如果用户lv6 next_exp的值会是 -- 这个需要注意下。

**Comment by JunzhouLiu** [comment]
> 有的api返回的值类型可能不一样，比如主站查询硬币余额的一个借口 余额可能会返回一个null ，个人信息的查询接口，如果用户lv6 next_exp的值会是 -- 这个需要注意下。

还有就是日志需要优化下，按理说这个异常不应该报账号信息相关的错误。

**Comment by RayWangQvQ** [comment]
> 有的api返回的值类型可能不一样，比如主站查询硬币余额的一个借口 余额可能会返回一个null ，个人信息的查询接口，如果用户lv6 next_exp的值会是 -- 这个需要注意下。

感谢提醒！之前我已经掉进过这几个坑了。。。
感觉B站的接口规范还是有优化空间的，第一个余额返回null勉强还说的过去，可能是不同接口是不同开发人员开发的，所以导致有的是0有的是null；但是第二个，同一个接口，同一个字段，有时返回数字有时返回字符串“--”就有点说不过去了。。。

**Comment by JunzhouLiu** [comment]
> > 有的api返回的值类型可能不一样，比如主站查询硬币余额的一个借口 余额可能会返回一个null ，个人信息的查询接口，如果用户lv6 next_exp的值会是 -- 这个需要注意下。
> 
> 感谢提醒！之前我已经掉进过这几个坑了。。。
> 感觉B站的接口规范还是有优化空间的，第一个余额返回null勉强还说的过去，可能是不同接口是不同开发人员开发的，所以导致有的是0有的是null；但是第二个，同一个接口，同一个字段，有时返回数字有时返回字符串“--”就有点说不过去了。。。

--代表的是无穷大的意思，这里都按str处理就好了，用的时候不是--的转成int

**Comment by RayWangQvQ** [comment]
@JunzhouLiu 异常管理这块确实需要再优化下，比如任务发生异常本应该不影响微信正常推送的（推送异常信息给用户）。
P.S.本想直接在你的项目下面贡献点自己的PR的，无奈我Java太菜，就用C#自己实现了，比如可以配置指定优先给哪些up主投币，配置调用B站API的最短时间间隔之类的，这些配置对我来说还是挺有用的，你也可以考虑下😄～

**Comment by JunzhouLiu** [comment]
> @JunzhouLiu 异常管理这块确实需要再优化下，比如任务发生异常本应该不影响微信正常推送的（推送异常信息给用户）。
> P.S.本想直接在你的项目下面贡献点自己的PR的，无奈我Java太菜，就用C#自己实现了，比如可以配置指定优先给哪些up主投币，配置调用B站API的最短时间间隔之类的，这些配置对我来说还是挺有用的，你也可以考虑下😄～

这块功能近期没打算做，倒不是因为实现上有多困难。

时间间隔的话，每秒不超过500次问题就不大，部分api是带limit字段的。
