### ISSUE TITLE
UserAgent 不能命令行参数化吗？

### ISSUE THREAD

**Issue by DaveBoy** [RayWangQvQ/BiliBiliTool#324]
我想通过quicker实现命令行启动，这样不一样的电脑(公司/家里)都可以一样了，而且不用更改下载下来的配置文件。
但是UserAgent好像无法通过命令行传入？[Constants.cs中没找到对应关系](https://github.com/RayWangQvQ/BiliBiliTool/blob/main/src/Ray.BiliBiliTool.Config/Constants.cs)

**Comment by RayWangQvQ** [comment]
第一，是因为UA太长了，写在命令行里很恶心；
第二，当前来看改UA不一定有什么作用，之前加上是因为有人说改UA可以解决偶发性412异常，但是后来发现412跟UA没有直接关系，现在不配置直接就用默认的应该也没问题的。

没有用过quicker，不了解用法，但既然它能执行启动命令，那是不是也能在启动命令前多执行一条添加环境变量的命令？如果可以的话，那完全可以通过添加环境变量来添加UA配置了。

**Comment by DaveBoy** [comment]
行  我试试设置环境变量
