### ISSUE TITLE
配置server酱的话Secret Name填什么

### ISSUE THREAD

**Issue by nileixing** [RayWangQvQ/BiliBiliTool#338]

**Comment by aorosora** [comment]
你开配置文件里面给的网址就行

**Comment by nileixing** [comment]
配置文件是哪个

**Comment by aorosora** [comment]
抱歉刚刚没说清楚，配置文件位置`BiliBiliTool/.github/workflows/bilibili-daily-task.yml`，从49行开始，你可以自己设置参数。
如果只要server酱的推送的话，新建一个名为`PUSHSCKEY`的Secret，然后下面填密钥就可以了。

**Comment by nileixing** [comment]
额谢谢
