### ISSUE TITLE
[Warning]一个投币的小问题

### ISSUE THREAD

**Issue by iloveyby** [RayWangQvQ/BiliBiliTool#339]
Tool Version : 1.0.14

Question:
工具已经稳定跑了10天了。今天上bilibili发现自己硬币竟然有5个， action显示也是正常的。在DEBUG模式下发现了投币的问题。
```{"code":137001,"message":"账号封禁中，无法完成操作","ttl":1,"data":{"like":false}}```
上面是投币返回的`content`，显示了账号被封禁。这个封禁在bilibili体系中无法被查看。也没有任何邮件提示，也没找不到任何说明（当然可能我没仔细找。）

工具这边可以做个判定，`code`返回`137001`的可以直接结束程序，避免多次请求。

账号封禁了，除了不能投币，不能发表评论，不能点赞，不能收藏，不能关注之外。其他还是正常的。这好像是除了看片啥都不能干了。

**Comment by RayWangQvQ** [comment]
v1.1.2已完成，很棒的一个建议，谢谢！
