### ISSUE TITLE
[建议]关于将程序做成docker镜像的构想

### ISSUE THREAD

**Issue by jiayaoO3O** [RayWangQvQ/BiliBiliTool#34]
虽然我觉得GitHub Action已经足够方便了, 但是打包成docker镜像之后, 只要一个docker run命令即可部署程序不是美滋滋

**Comment by Mr-Quin** [comment]
这个我做了一个试了试 感觉不如Github Action方便，可能是我不会做 你有兴趣也可以试一下
命令`docker run -t -d -v /PATH_TO_CONFIG:/bilibili/config  --name bilibilitool mrquin/bilibilitool`
`PATH_TO_CONFIG` 的部分替换为一个含有`appsettings.json`文件的目录 目录里可以有多个文件，只要是json结尾就行，BiliBiliTool会以每个文件的配置运行一次
我设置的cron是每天15点执行，每次容器启动也会执行一次
输出日志看`docker logs`

镜像用的是[aspnet3.1 amd64 debian](https://hub.docker.com/_/microsoft-dotnet-aspnet/)

**Comment by QianXun0827** [comment]
同觉得可以整一个docker镜像，这样子就不用去费心适配多个不同平台了

**Comment by hjkl950217** [comment]
@Mr-Quin 要不把dockerFile PR过来？ 这样可以一起维护

**Comment by Mr-Quin** [comment]
@hjkl950217  给了一个pr #273 含说明
我的镜像还是在`mrquin/bilibilitool` 你们如果开始支持docker的话我就可以把我的撤了

**Comment by hjkl950217** [comment]
> @hjkl950217 给了一个pr #273 含说明
> 我的镜像还是在`mrquin/bilibilitool` 你们如果开始支持docker的话我就可以把我的撤了

我还不是很懂docker，没能力view。。。

**Comment by RayWangQvQ** [comment]
v1.0.15已经合并了 @Mr-Quin 的PR，有些能优化的地方，后面可以再慢慢优化。

**Comment by GreenTeodoro839** [comment]
请问什么时候能在docker上使用？

**Comment by RayWangQvQ** [comment]
v1.2.1重构了下，使用docker-compose启动容器，使用环境变量添加配置，文档已更新到主README

**Comment by RayWangQvQ** [comment]
v1.2.1重构了下，使用docker-compose启动容器，使用环境变量添加配置，文档已更新到主README

**Comment by RayWangQvQ** [comment]
v1.2.1重构了下，使用docker-compose启动容器，使用环境变量添加配置，文档已更新到主README

**Comment by ptsa** [comment]
docker 第二天不能自动签 提示cookies 错误。 但是第一天是好的  重建下又可以

**Comment by RayWangQvQ** [comment]
> ocker 第二天不能自动签 提示cookies 错误。 但是第一天是好的 重建下又可以

是bug，测试了下，发现原来crontab默认读取不到所有环境变量。。。

**Comment by RayWangQvQ** [comment]
> docker 第二天不能自动签 提示cookies 错误。 但是第一天是好的 重建下又可以

@ptsa  已更新镜像，重新pull一下，应该就能解决这个问题了。

**Comment by github-xihe** [comment]
作者大大，请问docker版如何添加TG的推送

**Comment by RayWangQvQ** [comment]
> 作者大大，请问docker版如何添加TG的推送

添加配置就行了，跟Cookie一样，Cookie怎么配上去的，推送就怎么配上去。
