### ISSUE TITLE
分享视频是分享到哪里了？

### ISSUE THREAD

**Issue by LiboOfficial** [RayWangQvQ/BiliBiliTool#345]

**Comment by RayWangQvQ** [comment]
tan90°

**Comment by repairwa11** [comment]
分享动作没有真正完成。在B站的逻辑里，按下分享按钮，点一下站外图标即认为分享完成，事实上还需要后续操作才能真正完成分享。在本工具中，只需模拟点击分享按钮后点击复制链接按钮即可实现每日分享这个需求，无需拉动第三方app。

**Comment by nkh0472** [comment]
正常的分享流程：b站手机端点击分享按钮-调用第三方app-(第三方app返回是否分享成功，如QQ；但某些app不会返回消息，因此调用成功就算完成，如微信)-b站手机端通过api告知服务器今日已分享

可以看到最后一步“b站手机端通过api告知服务器今日已分享”中，服务器本身并不知道分享的目的地（但点击被分享的链接可以跟踪，此处不表）。

本软件仅实现了最后一步，“通过api告知服务器今日已分享”，而分享动作本身没有发生。

解决问题请及时关闭issue。
