### ISSUE TITLE
v1.1.1使用命令行参数配置Server酱失效

### ISSUE THREAD

**Issue by chen-yixin** [RayWangQvQ/BiliBiliTool#352]
运行环境: Debian 10 ARM64, RaspberryPi 3B+,  已安装dotnet sdk 5.0.101 (linux-arm64)
git拉取代码之后自行编译，部署在树莓派上
命令: `dotnet publish --configuration Release --runtime linux-arm64 --self-contained false -o ./bin/Publish/linux-arm64`

运行完之后，微信上没有收到Server酱的消息，
作为对比，拉取`1.0.17`tag之后，用同样的命令编译，部署，执行，就可以收到Server酱消息

**Comment by chen-yixin** [comment]
补充，拉取`1.1.1`tag发现Server酱失效

**Comment by RayWangQvQ** [comment]
v1.1.x之后重新定义了推送的概念，但是命令行映射忘记修改了，可以自己改下这个文件：
![image](https://user-images.githubusercontent.com/31154238/103435694-4ba17f80-4c4d-11eb-9cee-21b350e5f1d9.png)

本地部署的话不推荐使用命令行添加配置，可以直接修改json文件了，或者可以使用环境变量的形式来实现配置：
`export Ray_Serilog:WriteTo:6:Args:scKey=scKey`
环境变量名称可以参考bilibili-daily-task.yml文件

**Comment by chen-yixin** [comment]
使用export语句情况下，变量名里有`:`的话，提示不合法标识符
有没有什么好的方法在shell脚本里加载含有`:`的环境变量？
![屏幕截图 2021-01-01 182800](https://user-images.githubusercontent.com/47199142/103437201-74327500-4c5f-11eb-92e1-cede743b3d25.png)

**Comment by RayWangQvQ** [comment]
这个之前倒是没有考虑到，抱歉。
下个版本（v1.1.2）会支持双下滑线，`Ray_Serilog__WriteTo__6__Args__scKey=scKey`这种，预计今晚或明天会和其他bug一起修复、发布。
如果你比较着急的话，建议先使用json文件配置，或改commandLineMappings.json文件后使用命令行配置。

**Comment by RayWangQvQ** [comment]
v1.1.2已完成

**Comment by chen-yixin** [comment]
拉取v1.1.2代码后重新打包运行，使用命令行和环境变量的2种方式各试了一次。
都可以正常收到Server酱消息
感谢大佬
