### ISSUE TITLE
1.1.1版本，给指定up主投币失效？

### ISSUE THREAD

**Issue by LiboOfficial** [RayWangQvQ/BiliBiliTool#355]
仍然还是给默认的作者本人B站Id投币？以下是填写的配置，是填写有问题吗？
![屏幕截图 2021-01-01 211520](https://user-images.githubusercontent.com/76651600/103439385-6e488e00-4c77-11eb-8f7f-80a106803fad.png)
![屏幕截图 2021-01-01 211553](https://user-images.githubusercontent.com/76651600/103439386-6f79bb00-4c77-11eb-9365-31202a9be9e8.png)

**Comment by RayWangQvQ** [comment]
v1.0.15时重构了配置框架，加入了环境的概念：
![image](https://user-images.githubusercontent.com/31154238/103441529-9fca5500-4c89-11eb-8d9c-02207f6151e9.png)

简单说，就是生产环境中，appsettings.Production.json 优先级高于 appsettings.json，你可以直接把 appsettings.Production.json 这个文件删了，或者在 appsettings.Production.json 当中进行个人配置。

详细信息可以参考[配置说明文档](https://github.com/RayWangQvQ/BiliBiliTool.Docs/blob/main/configuration.md)：

![image](https://user-images.githubusercontent.com/31154238/103441608-16ffe900-4c8a-11eb-9b50-d252b3ec9e2c.png)
df

P.S.你这配了这么多Id都不想配我的，这么大的仇嘛💔
