### ISSUE TITLE
大佬们求助呀qwq

### ISSUE THREAD

**Issue by 1736698520** [RayWangQvQ/BiliBiliTool#356]
这咋整
![QQ截图20210101221029](https://user-images.githubusercontent.com/76840751/103440157-401a7c80-4c7e-11eb-852c-47f2f2029f25.png)

**Comment by RayWangQvQ** [comment]
升级最新版

**Comment by 1736698520** [comment]
> 升级最新版

整好了，谢谢大佬，公众号老版本害死人
