### ISSUE TITLE
[需求]多账号签到

### ISSUE THREAD

**Issue by LittleBlacklb** [RayWangQvQ/BiliBiliTool#358]
由于是在action上运行 只能签到一个账号 所以希望能添加多个账号进行签到

**Comment by LittleBlacklb** [comment]
当然我后面又在bilibili-daily-task.yml中最后一行添加了并且在secret中添加了新的cookie也是可以做到多账号签到的
dotnet Ray.BiliBiliTool.Console.dll -userId=${{secrets.USERID_2}} -sessData=${{secrets.SESSDATA_2}} -biliJct=${{secrets.BILIJCT_2}} -closeConsoleWhenEnd=1 ${{secrets.OTHERCONFIGS}}
但是总感觉有点违和感233

**Comment by RayWangQvQ** [comment]
与 #53 重复，暂时没有支持多账号的计划

**Comment by LittleBlacklb** [comment]
thx
