### ISSUE TITLE
停用1个月脚本后重新启用脚本3天就收到警告

### ISSUE THREAD

**Issue by Huli-fox** [RayWangQvQ/BiliBiliTool#367]
之前在12月1号17点收到警告后立刻停用，1月1日重新启用，今天19点就收到警告了。才用3天，被警告2次了，有点慌

**Comment by yinghualuowu** [comment]
实际上一共就警告了两次。一次12月1号，一次1月4号。这种警告应该是统一的，我也收到了。不是说用了几天就会警告的~。

**Comment by RayWangQvQ** [comment]
与 #253 重复，警告一次，不符合issues提价规范的会被删除，严重的会进行拉黑处理。
