### ISSUE TITLE
程序异常

### ISSUE THREAD

**Issue by DollyDino9** [RayWangQvQ/BiliBiliTool#381]
今早八点半推送程序异常，大大更新下脚本

**Comment by RayWangQvQ** [comment]
#384

**Comment by ipx2001** [comment]
我的也是今天发出警告了！
![QQ截图20210105121311](https://user-images.githubusercontent.com/53973303/103605687-86f2c580-4f4f-11eb-92fd-9e9ebe198538.jpg)

**Comment by DollyDino9** [comment]
等作者大大更新吧
