### ISSUE TITLE
黑名单公示

### ISSUE THREAD

**Issue by RayWangQvQ** [RayWangQvQ/BiliBiliTool#384]
以下6人因不遵守issue提交规范，待会儿会统一被拉入黑名单，被拉入黑名单的人将不能fork该仓库。

![黑名单图示](https://user-images.githubusercontent.com/31154238/103600181-cf0aeb80-4f41-11eb-80df-2df31d7ced86.png)

![黑名单图示](https://images.cnblogs.com/cnblogs_com/RayWang/1874052/o_210105024404BiliBiliTool%E9%BB%91%E5%90%8D%E5%8D%95.png)

黑名单图示：https://images.cnblogs.com/cnblogs_com/RayWang/1874052/o_210105024404BiliBiliTool%E9%BB%91%E5%90%8D%E5%8D%95.png

如有错判，请在该条issue下回复或私信我。

**Comment by 837468220** [comment]
访问 images.cnblogs.com 的请求遭到拒绝您未获授权，无法查看此网页。
HTTP ERROR 403

**Comment by zhy0715** [comment]
你这种辣鸡开发者，没人愿意用你这破程序

**Comment by RayWangQvQ** [comment]
> 你这种辣鸡开发者，没人愿意用你这破程序

刚才其实只是警告，并没有真的拉黑任何人，目前只决定拉黑你一个~

因为我想了一下，其他人可能只是无心的（或不懂 GitHub 里的 issues 应该怎么用），但是你不是。

希望你能说到做到，以后不要再用这破程序，谢谢。

**Comment by RayWangQvQ** [comment]
> 你这种辣鸡开发者，没人愿意用你这破程序

![image](https://user-images.githubusercontent.com/31154238/103616301-1d7eb100-4f67-11eb-984c-21af3babbfcc.png)

`wysnxzm` 点赞了这条，那我默认你也有相同的想法，所以也帮你拉进来了，希望我没有意会错你的意思，如果错了请告诉我。

列表+2：

![image](https://user-images.githubusercontent.com/31154238/103616480-7d755780-4f67-11eb-91eb-c12985ff8a11.png)

**Comment by RayWangQvQ** [comment]
> 你这种辣鸡开发者，没人愿意用你这破程序

![image](https://user-images.githubusercontent.com/31154238/103616301-1d7eb100-4f67-11eb-984c-21af3babbfcc.png)

@wysnxzm 点赞了这条，那我默认你也有相同的想法，所以也帮你拉进来了，希望我没有意会错你的意思，如果错了请告诉我。

列表+2：

![image](https://user-images.githubusercontent.com/31154238/103616480-7d755780-4f67-11eb-91eb-c12985ff8a11.png)

**Comment by DollyDino9** [comment]
作者大大不好意思啊，我每次都是遇到bug第一时间去提交问题的，不懂这个功能不可以重复提交，今天中午我把我那个评论关闭了，希望没有影响，大大不好意思了。

**Comment by RayWangQvQ** [comment]
> 作者大大不好意思啊，我每次都是遇到bug第一时间去提交问题的，不懂这个功能不可以重复提交，今天中午我把我那个评论关闭了，希望没有影响，大大不好意思了。

收到。

还是感谢你`每次都是遇到bug第一时间去提交问题`，你们的反馈和建议会让开源程序优化的越来越完善。

但为了使 issues 下面的议题便于维护，便于其他人搜索查找历史议题，避免淹没在一堆**无用或重复**的 issues 里，重复的最好不要反复提了，可以到对应问题下面回复，也方便其他人一起集中浏览。

**Comment by DollyDino9** [comment]
好的，了解！
