### ISSUE TITLE
login exception（登录异常，提示"登录失败，请检查Cookie"）

### ISSUE THREAD

**Issue by dhtcdh** [RayWangQvQ/BiliBiliTool#392]
[17:32:30 WRN] 登录异常，Cookies可能失效了，请仔细检查Github Secrets中DEDEUSERID、SESSDATA、BILI_JCT三项的值是否正确
[17:32:30 ERR] 程序发生异常：登录失败，请检查Cookie
[17:32:30 ERR] 程序异常终止，原因：登录失败，请检查Cookie
I'm sure there's no problem with this cookie, because it can be done before

**Comment by kasohong** [comment]
I have the same problem,version 1.1.4

**Comment by RayWangQvQ** [comment]
What value the `OtherCookies` Configuration is？

https://github.com/RayWangQvQ/BiliBiliTool/issues/364

**Comment by Origin-CN** [comment]
同遇到此问题，在添加OtherCookies后恢复正常

**Comment by PurBlu** [comment]
+1
换用重新登陆后的bili_jct与SESSDATA以后仍然提示:

[20:54:39 INF] ---开始【登录】---
[20:54:43 WRN] 登录异常，Cookies可能失效了，请仔细检查Github Secrets中DEDEUSERID、SESSDATA、BILI_JCT三项的值是否正确
[20:54:43 ERR] 程序发生异常：登录失败，请检查Cookie
[20:54:43 ERR] 程序异常终止，原因：登录失败，请检查Cookie

OtherCookies添加后正常运行

**Comment by feiying1** [comment]
一样报错134
![1](https://user-images.githubusercontent.com/58288127/103685974-0d97b900-4fc9-11eb-9113-3842f07a438b.png)

**Comment by horse-farmer** [comment]
多次更新cookies参数之后运行github action还是提示：
20:54:39 INF] --- 开始【登录】---
[20:54:43 WRN] 登录异常，Cookies 可能失效了，请仔细检查 Github Secrets 中 DEDEUSERID、SESSDATA、BILI_JCT 三项的值是否正确
[20:54:43 ERR] 程序发生异常：登录失败，请检查 Cookie
[20:54:43 ERR] 程序异常终止，原因：登录失败，请检查 Cookie

代码也手动pr到最新版本，不知道作者是不是有发现这个问题

**Comment by zhangblin** [comment]
OtherCookies 值取自哪里？

**Comment by feiying1** [comment]
Cookies界面的随便一个，我选的是第一个------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;张保林&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月6日(星期三) 下午5:54
收件人:&nbsp;&quot;RayWangQvQ/BiliBiliTool&quot;<BiliBiliTool@noreply.github.com&gt;;
抄送:&nbsp;&quot;feiying1&quot;<dsk_hm@foxmail.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliTool] login exception (#392)

**Comment by dlxbf** [comment]
同问题 求解决办法

**Comment by DollyDino9** [comment]
> 同遇到此问题，在添加OtherCookies后可正常运行

OtherCookies的值怎么取？

**Comment by DollyDino9** [comment]
> +1
> 换用重新登陆后的bili_jct与SESSDATA以后仍然提示:
> 
> [20:54:39 INF] ---开始【登录】---
> [20:54:43 WRN] 登录异常，Cookies可能失效了，请仔细检查Github Secrets中DEDEUSERID、SESSDATA、BILI_JCT三项的值是否正确
> [20:54:43 ERR] 程序发生异常：登录失败，请检查Cookie
> [20:54:43 ERR] 程序异常终止，原因：登录失败，请检查Cookie
> 
> OtherCookies添加后正常运行
OtherCookies的值如何取呢？

**Comment by DollyDino9** [comment]
> +1
> 换用重新登陆后的bili_jct与SESSDATA以后仍然提示:
> 
> [20:54:39 INF] ---开始【登录】---
> [20:54:43 WRN] 登录异常，Cookies可能失效了，请仔细检查Github Secrets中DEDEUSERID、SESSDATA、BILI_JCT三项的值是否正确
> [20:54:43 ERR] 程序发生异常：登录失败，请检查Cookie
> [20:54:43 ERR] 程序异常终止，原因：登录失败，请检查Cookie
> 
> OtherCookies添加后正常运行



> +1
> 换用重新登陆后的bili_jct与SESSDATA以后仍然提示:
> 
> [20:54:39 INF] ---开始【登录】---
> [20:54:43 WRN] 登录异常，Cookies可能失效了，请仔细检查Github Secrets中DEDEUSERID、SESSDATA、BILI_JCT三项的值是否正确
> [20:54:43 ERR] 程序发生异常：登录失败，请检查Cookie
> [20:54:43 ERR] 程序异常终止，原因：登录失败，请检查Cookie
> 
> OtherCookies添加后正常运行
OtherCookies的值怎么取？

**Comment by feiying1** [comment]
请看这解决https://github.com/RayWangQvQ/BiliBiliTool/issues/364------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;满心欢喜&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月7日(星期四) 中午1:03
收件人:&nbsp;&quot;RayWangQvQ/BiliBiliTool&quot;<BiliBiliTool@noreply.github.com&gt;;
抄送:&nbsp;&quot;feiying1&quot;<dsk_hm@foxmail.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliTool] login exception (#392)

**Comment by Origin-CN** [comment]
> > 同遇到此问题，在添加OtherCookies后可正常运行
> 
> 
> 
> OtherCookies的值怎么取？

请参考[该议题](https://github.com/RayWangQvQ/BiliBiliTool/issues/364)

**Comment by TosakaUCW** [comment]
本地 win10 在添加 OtherCookies 以后可以正常运行，但是 github action 登录异常...

**Comment by Mreblack** [comment]
能问一下csrf校验失败是怎么回事吗

**Comment by dhtcdh** [comment]
额 还是这个错误.&nbsp;&nbsp;是刚刚拉取更新后运行的
```
[09:12:11 WRN] 登录异常，Cookies可能失效了，请仔细检查Github Secrets中DEDEUSERID、SESSDATA、BILI_JCT三项的值是否正确

[09:12:11 ERR] 程序发生异常：登录失败，请检查Cookie

[09:12:11 ERR] 程序异常终止，原因：登录失败，请检查Cookie


```
&nbsp;

&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliTool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月10日(星期天) 上午10:18
收件人:&nbsp;"RayWangQvQ/BiliBiliTool"<BiliBiliTool@noreply.github.com&gt;;
抄送:&nbsp;"皇天极"<357000879@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliTool] login exception (#392)





 
能问一下csrf校验失败是怎么回事吗

**Comment by dhtcdh** [comment]
实测可以用了,添加了&nbsp;OtherCookies 后网页上的action就可以用了.
OtherCookies&nbsp; 的获取方法很简单,登录后打开一个网页,然后把接口里面的
Request Headers
里面的
cookie的值复制过去就可以了







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mreblack7"<notifications@github.com&gt;; 
发送时间: 2021年1月10日(星期天) 上午10:18
收件人: "RayWangQvQ/BiliBiliTool"<BiliBiliTool@noreply.github.com&gt;; 
抄送: "皇天极"<357000879@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [RayWangQvQ/BiliBiliTool] login exception (#392)





 
能问一下csrf校验失败是怎么回事吗

**Comment by RayWangQvQ** [comment]
> 能问一下csrf校验失败是怎么回事吗

Cookie过期了（手动退出账号会导致过期），重新抓取下更新到配置就行了。

**Comment by zhaojieip** [comment]
F12后在接口里面讲cooke的值全部复制，在添加OtherCookies参数。
一共三个参数。这样的对应关系，完美解决
Secret      	Cookie 	         Value
USERID	        DEDEUSERID	    xxx
SESSDATA	SESSDATA	    xxx
BILIJCT	        BILI_JCT	            xxx
OtherCookies  cookie                 xxx
