### ISSUE TITLE
【建议】更新一下v1.1.4对于OTHERCOOKIES的文档说明

### ISSUE THREAD

**Issue by GitHubBean** [RayWangQvQ/BiliBiliTool#401]
建议内容：
最新版本的v1.1.4，为了解决412做了升级处理，添加了OTHERCOOKIES；
**### 如果仅仅只配置DEUSERID、SESSDATA、BILI_JCT三项，会提示“登录异常，Cookies可能失效了”**

参见 #364 

up加油 ^_^

**Comment by RayWangQvQ** [comment]
已更新。
