### ISSUE TITLE
【Bug】请清晰地描述你遇到的异常或缺陷

### ISSUE THREAD

**Issue by din-ning** [RayWangQvQ/BiliBiliTool#412]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决问题？）
运行环境：（请贴出运行环境，比如是Actions还是本地？Win还是Linux？）

问题描述：（提issue前请确认没有其他人已提过相同的，重复提交会被删除，严重的会进行拉黑处理！请清晰的描述所遇到的异常信息。）

日志信息：（请贴出Debug级别的日志信息，不是Debug级别的日志如果不具有参考价值，会被关闭，严重的会被删除。）

**Comment by RayWangQvQ** [comment]
请说明乱提issue的原因，否则稍后进行拉黑处理。
