### ISSUE TITLE
我来帮大家总结下Server酱的配置方法

### ISSUE THREAD

**Issue by djangoIee** [RayWangQvQ/BiliBiliTool#44]
首先感谢作者提供这个工具，🙏 因为这个问题最近问的比较多，所以为大家总结一下：

### 1. 登陆Server酱，绑定github和微信，具体参考官网，在后在下图的页面获取到SCKEY, 此处假设其值为 ABCDEFG

![image](https://user-images.githubusercontent.com/15151031/99059344-6e160580-25d9-11eb-99f1-4ed941e98ed9.png)

### 2. 打开自己fork的项目的下图位置添加新的secret

![image](https://user-images.githubusercontent.com/15151031/99059542-b59c9180-25d9-11eb-876b-635524f30eea.png)

### 3. 输入Name为 ```OTHERCONFIGS``` , Value为 ``` -PushScKey=ABCDEFG ``` ,请注意将ABCDEFG替换为自己第一步获取的值

![image](https://user-images.githubusercontent.com/15151031/99061186-22189000-25dc-11eb-8ae3-f9d5a9180acb.png)

**Comment by RayWangQvQ** [comment]
总结棒啊，已置顶给需要的朋友。
另外，可以整理下PR到文档里的~

**Comment by djangoIee** [comment]
谢谢作者肯定😁

**Comment by RayWangQvQ** [comment]
当前版本（V1.0.9）已对配置进行了优化，不建议再将其他配置拼接到 OtherConfigs 的 Secret 里，建议直接单独添加微信推送的Secret，详细信息可查看 [配置说明文档](https://github.com/RayWangQvQ/BiliBiliTool.Docs/blob/main/configuration.md)

**Comment by hjkl950217** [comment]
恩。。现在可以很简单的配置了。这个可以关闭了
