### ISSUE TITLE
建议新增自动同步上游原作者仓库代码的功能

### ISSUE THREAD

**Issue by KarewaGron** [RayWangQvQ/BiliBiliTool#45]
希望能加自动更新的功能
![Screenshot_20201114_073421_com thirtydegreesray openhub](https://user-images.githubusercontent.com/67790796/99131294-bbcc5580-264d-11eb-9449-5ee4972230ba.jpg)
https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/8

**Comment by JunzhouLiu** [comment]
@KarewaGron @RayWangQvQ 这里有更有好的方案，使用 [Pull APP](https://github.com/apps/pull)

**Comment by KarewaGron** [comment]
> @KarewaGron @RayWangQvQ 这里有更有好的方案，使用 [Pull APP](https://github.com/apps/pull)

好家伙

**Comment by drw2005** [comment]
> @KarewaGron @RayWangQvQ 这里有更有好的方案，使用 [Pull APP](https://github.com/apps/pull)
好东西，谢谢！

**Comment by wangfeng-1** [comment]
> @KarewaGron @RayWangQvQ 这里有更有好的方案，使用 [Pull APP](https://github.com/apps/
giao~giao~

**Comment by wangfeng-1** [comment]
> @KarewaGron @RayWangQvQ 这里有更有好的方案，使用 [Pull APP](https://github.com/apps/pull)

giao~giao~

**Comment by RayWangQvQ** [comment]
默认提供三种同步方式：手动、GitHub Actions、PullAPP，详情见文档。
