### ISSUE TITLE
Centos报错The SSL connection could not be established

### ISSUE THREAD

**Issue by yeminch** [RayWangQvQ/BiliBiliTool#46]
Centos报错：The SSL connection could not be established

**Comment by RayWangQvQ** [comment]
有群友反馈，通过设置环境变量`export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0;`可以解决。

**Comment by RayWangQvQ** [comment]
相关链接：
http://blog.yshizi.cn/178.html
https://www.cnblogs.com/leoxjy/p/10201046.html
https://cloud.tencent.com/developer/ask/219559
