### ISSUE TITLE
【Bug】通过actions启动完成后需要每天重新手动启动workflow

### ISSUE THREAD

**Issue by nezha-santaizi** [RayWangQvQ/BiliBiliTool#468]
每天通过actions启动完成执行完成后，第二天就需要重新启动workflow，不能直接触发启动执行workflow么？

**Comment by RayWangQvQ** [comment]
https://hub.fastgit.org/RayWangQvQ/BiliBiliTool.Docs/blob/main/questions.md#3-actions%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1%E6%B2%A1%E6%9C%89%E6%AF%8F%E5%A4%A9%E8%87%AA%E5%8A%A8%E8%BF%90%E8%A1%8C

**Comment by nezha-santaizi** [comment]
> https://hub.fastgit.org/RayWangQvQ/BiliBiliTool.Docs/blob/main/questions.md#3-actions%E5%AE%9A%E6%97%B6%E4%BB%BB%E5%8A%A1%E6%B2%A1%E6%9C%89%E6%AF%8F%E5%A4%A9%E8%87%AA%E5%8A%A8%E8%BF%90%E8%A1%8C

我在改了wiki 还是没有自动运行

**Comment by GreenTeodoro839** [comment]
我记得在action界面，选上你执行的那个，然后点一下开头是enable的按钮
