### ISSUE TITLE
只有我是顺着公众号的推荐来的吗。。

### ISSUE THREAD

**Issue by hhhllll888** [RayWangQvQ/BiliBiliTool#47]
https://mp.weixin.qq.com/s/C4ysaR3vL4HUQm8a5uSfZQ

**Comment by RayWangQvQ** [comment]
这个什么公众号啊，第一没有贴源链接，第二他自己的截图上投币都是失败的。。。

**Comment by hhhllll888** [comment]
不知道，我在微信公众号里问他他都不回
