### ISSUE TITLE
【建议】对达到「投币上限」的视频停止投币

### ISSUE THREAD

**Issue by seiuneko** [RayWangQvQ/BiliBiliTool#474]
日志里会出现 

> ❗️ 尝试为“"【无节操字幕计划】那些游戏中不能说的秘密 Dorkly恶搞合集 5P 补完中"”投币失败，原因："超过投币上限啦~"

类似的内容。
可能这样会增加特征，希望能记录已达到投币上限的视频，并停止尝试投币。

**Comment by RayWangQvQ** [comment]
其实是已经有验证了的，只是这个验证可能有问题。

一开始测的时候，发现对单个视频的上限额度是2枚硬币，所以应用里，在投币前会先获取对目标视频的已投币个数，如果小于2就尝试投币。

现在看来，并不是这样，有些视频的投币上限额度其实是1枚，目前看和是否是原创视频有关，其他因素还要再查下。

计划在下个版本会进行优化。

**Comment by RayWangQvQ** [comment]
已于v1.1.6修复，会根据目标视频是否远程只能判断，如果非原创，则上限为1个币，已投满则不去重复投。
