### ISSUE TITLE
【建议】请问本地版如何升级？以及怎样在树莓派上部署这个的docker版

### ISSUE THREAD

**Issue by GreenTeodoro839** [RayWangQvQ/BiliBiliTool#479]
我用的本地版，每次想升级程序总不能全部删除，在复制粘贴一大堆配置吧。还有树莓派怎么用docker版，我看到issues里的是amd64（树莓派是arm64，已经安装好了docker）

**Comment by nkh0472** [comment]
本地升级时覆盖appsettings.json以外的所有文件即可

**Comment by RayWangQvQ** [comment]
已更新docker的部署文档，详见主页README
