### ISSUE TITLE
【建议】可否增加“今日已签到过”功能

### ISSUE THREAD

**Issue by nkh0472** [RayWangQvQ/BiliBiliTool#481]
建议内容：
    在程序运行最开始处（输出版本号后）检查今日是否已签到，若已签到即给出提示。用以提示手动本地运行签到的、健忘的我……
    实现方法或可通过目录下的时间戳临时文件实现，时间戳为上一次完成运行后（所有签到项目结束后，推送前）保存。

**Comment by RayWangQvQ** [comment]
每日任务里，大部分任务都是幂等的，运行多次也没有什么影响吧。

比如投币，目标如果是3个，投满之后再运行就不会投了；观看、分享视频也一样。

个人觉得暂时没必要做成带持久化数据、带状态的。
