### ISSUE TITLE
【Bug】添加secret 修改ISSKIPDAILYTASK值为false后 退出代码为134

### ISSUE THREAD

**Issue by tallmountain2** [RayWangQvQ/BiliBiliTool#482]
提交了很多新的github secrets 按照文档输入 有充电对象 sckey等key  看了下日志 好像改了之后每天运行都没成功（汗  遂删掉所有新加的secret  仍然收到错误邮件  之前也有类似提示ubuntu工作流程版本不够的问题 但是用了pull应用拉取后就解决了 这次一直不能解决 各位给看看
![2021-1-30 22-5-13](https://user-images.githubusercontent.com/41677247/106360127-bc71af80-6351-11eb-842d-4a1ab71bf0b2.png)

**Comment by RayWangQvQ** [comment]
![image](https://user-images.githubusercontent.com/31154238/106687694-9e34d980-6607-11eb-83c7-603aa77efef4.png)

上面是你的配置，我只看到你配置了3个cookie项和Server酱推送的配置。

请按照文档说明进行配置，当前版本不建议再配置3个cookie项了，推荐直接配置一个完整的CookieStr。

如果非要配置3个cookie项，请再额外配置一个OtherCookie，原因在这 https://github.com/RayWangQvQ/BiliBiliTool/issues/364
