### ISSUE TITLE
【建议】希望再改进下吧，今天被封了

### ISSUE THREAD

**Issue by LeviAcman** [RayWangQvQ/BiliBiliTool#487]
建议内容：
（提issue前请确认没有其他人提过相同的，重复提交会被删除，严重的会进行拉黑处理！）
被封禁七天，也改过默认签到时间了，是给自己设置的up主投币太多的问题吗

**Comment by hupo22** [comment]
啊，刚刚也被封了7天

**Comment by AutismYu** [comment]
我的也是，我好像都没设置，是默认的，也被封了7天，我查看了日志，我是大概0点左右（16小时前）运行的，怎么现在（15点多）发送的b站系统提醒

**Comment by LeviAcman** [comment]
不知道是不是4小时前的更新有关系

**Comment by hupo22** [comment]
我是上午运行，刚刚封的

**Comment by imldy** [comment]
被B站封了，但是意外的是账号仍然可以登录、观看视频、点赞、收藏，只不过不能发弹幕、发评论、点关注。
但是这个脚本做的事就是自动化登录、观看、点赞、投币、收藏，所以脚本经常做的事没被封（除了投币），反倒正常使用的功能被封了。
封号表现有点迷，也没有明确的说明封号之后会被限制的功能，客服也不知道。
