### ISSUE TITLE
【Bug】412异常

### ISSUE THREAD

**Issue by GitHubBean** [RayWangQvQ/BiliBiliTool#489]
版本号：2021-02-06 1.1.4 最新版本
运行环境：github action

问题描述：412异常 以及 分享失败：Object reference not set to an instance of an object.

日志信息：❗ null失败，继续其他任务。失败信息:"Response status code does not indicate success: 412 (Precondition Failed)."
❗ "观看、分享视频"失败，继续其他任务。失败信息:"Object reference not set to an instance of an object."

（投币失败，帐号已被封禁，上诉问题难道是跟帐号被封禁有关？）

**Comment by RayWangQvQ** [comment]
是的，封禁账号无法完成这些任务。
