### ISSUE TITLE
【建议】建议投币的时候可以投币给自己关注的UP投，或者是在最近自己看的视频里面投

### ISSUE THREAD

**Issue by gejiawei007** [RayWangQvQ/BiliBiliTool#49]
【建议】建议投币的时候可以投币给自己关注的UP投，或者是在最近自己看的视频里面投

**Comment by RayWangQvQ** [comment]
后续版本会添加的。
另外，[#16 issue](https://github.com/RayWangQvQ/BiliBiliTool/issues/16)下已经有朋友讨论很多相关信息了，可以转到那里参与讨论~
