### ISSUE TITLE
【Bug】自动签到失败

### ISSUE THREAD

**Issue by Thomitics** [RayWangQvQ/BiliBiliTool#490]
版本号：1.1.5
运行环境：Actions

问题描述：自动签到失败

日志信息：
[08:30:49 INF] ---开始【登录】---
[08:30:53 INF] 登录成功，经验+5 √
[08:30:53 INF] 用户名: 芊枫T*****ics
[08:30:53 INF] 硬币余额: 4***5.3
[08:30:53 INF] 如每日做满65点经验，距离升级到Lv5还有: 77天
[08:30:53 INF] ---结束---

[08:30:57 ERR] null失败，继续其他任务。失败信息:Response status code does not indicate success: 4***2 (Precondition Failed).

[08:30:57 INF] ---开始【观看、分享视频】---
[08:30:57 ERR] 观看、分享视频失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

**Comment by wxyttty** [comment]
可能是cookiestr问题，我1.1.6的也是，删除了bili_jct=...;后的cookie就可以了

**Comment by feng6606** [comment]
我出现的问题是  自定义配置 错误 请更换 UA

**Comment by RayWangQvQ** [comment]
请更新到最新版（v1.2.0）尝试修复，更新方法可以参考常见问题文档。

**Comment by wxyttty** [comment]
1.2
>       登录异常，请检查Cookie是否错误或过期
[23:29:*** ERR] 程序发生异常：登录失败，请检查Cookie
[23:29:*** ERR] 程序异常终止，原因：登录失败，请检查Cookie
[23:29:*** INF] 开始推送
[23:29:*** INF] 正在自动关闭应用...
[23:29:*** FTL] Host terminated unexpectedly!
System.Exception: 登录失败，请检查Cookie

**Comment by RayWangQvQ** [comment]
> 1.2
> 
> > ```
> >   登录异常，请检查Cookie是否错误或过期
> > ```
> 
> [23:29:*** ERR] 程序发生异常：登录失败，请检查Cookie
> [23:29:*** ERR] 程序异常终止，原因：登录失败，请检查Cookie
> [23:29:*** INF] 开始推送
> [23:29:*** INF] 正在自动关闭应用...
> [23:29:*** FTL] Host terminated unexpectedly!
> System.Exception: 登录失败，请检查Cookie

我在想，这不是提示的已经很清楚了吗

**Comment by wxyttty** [comment]
只要退回1.1.6立刻OK

**Comment by Thomitics** [comment]
> > 1.2
> > > ```
> > >   登录异常，请检查Cookie是否错误或过期
> > > ```
> > 
> > 
> > [23:29:*** ERR] 程序发生异常：登录失败，请检查Cookie
> > [23:29:*** ERR] 程序异常终止，原因：登录失败，请检查Cookie
> > [23:29:*** INF] 开始推送
> > [23:29:*** INF] 正在自动关闭应用...
> > [23:29:*** FTL] Host terminated unexpectedly!
> > System.Exception: 登录失败，请检查Cookie
> 
> 我在想，这不是提示的已经很清楚了吗？更新以下Cookie再试试？

更新过了，不管用

**Comment by RayWangQvQ** [comment]
随便翻了下今天Fork的人的运行日志，都是v1.2.0，都运行成功了：

https://github.com/cn0068/BiliBiliTool/runs/1883419510?check_suite_focus=true
https://github.com/reoyf/BiliBiliTool/runs/1883198194?check_suite_focus=true
https://github.com/m1n9o/BiliBiliTool/runs/1881461911?check_suite_focus=true
https://github.com/zhgggg/BiliBiliTool/runs/1881152892?check_suite_focus=true
https://github.com/garrettdo/BiliBiliTool/runs/1878974940?check_suite_focus=true

找下自己原因吧，如果提示“Cookie过期”那就是字面意思，要不就是过期了，要不就是配置错了。

建议更新配置时仔细对比下配置值和浏览器里的值是否相同（不要相信拷贝就一定一摸一样，有些浏览器插件或电脑里的流氓软件会“优化”拷贝内容），**尤其关注Cookie里的`SESSDATA`和`bili_jct`两项**。

**Comment by wxyttty** [comment]
不可能过期或者错误，当天登录后复制的cookie。复制十几次了，反复确认过，微软自带输入法，edge，并且退回1.1.6后，还是粘贴同样的cookie，可以运行

**Comment by RayWangQvQ** [comment]
那只能把Cookie发给我我来帮你调试了

**Comment by RayWangQvQ** [comment]
## 达瓦里希：
有了新的进展，刚才群里正好有个朋友反馈遇到了同样的问题，于是我跟他要来Cookie调试了下，最后发现是浏览器问题，导致拿到的Cookie不正确，更换浏览器后再更新一次就成功了：

![image](https://user-images.githubusercontent.com/31154238/107764045-7ca3c280-6d6a-11eb-89db-06d8c4f87d2c.png)

总结几点注意项：
* 推荐使用Edge浏览器，其次谷歌（Chrome），其他均不推荐，尤其某些国产辣鸡浏览器
* 请使用最新文档中配置Cookie的方式（配置完整的字符串到`CookieStr`配置项）
* 请使用最新文档中获取Cookie的方式（登录后通过访问`https://api.bilibili.com/x/web-interface/nav`获取）
* 如果还不行，请重新登录后再获取Cookie

@Thomitics @wxyttty

**Comment by wxyttty** [comment]
是edge，也是nav获取的，反正1.1.6可以用就好

**Comment by Thomitics** [comment]
浏览器：
![image](https://user-images.githubusercontent.com/62173814/107767801-87615600-6d70-11eb-9e87-b4b0fe990a71.png)
手动复制了一遍cookie，不用Edge右键的Copy Value，就可以了

**Comment by Thomitics** [comment]
不过过几天可能又失效，我再看看吧

**Comment by Thomitics** [comment]
Microsoft Edge | 90.0.795.0 (官方内部版本) canary (64 位)
-- | --
修订 | bfe8e408078be7996356f438f3aab3358e575e68
操作系统 | Windows 10 OS Version 2009 (Build 19042.804)
JavaScript | V8 9.0.138
用户代理 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4412.0 Safari/537.36 Edg/90.0.795.0

**Comment by RayWangQvQ** [comment]
> 浏览器：
> ![image](https://user-images.githubusercontent.com/62173814/107767801-87615600-6d70-11eb-9e87-b4b0fe990a71.png)
> 手动复制了一遍cookie，不用Edge右键的Copy Value，就可以了

被你破案了！右击拷贝值的话，浏览器会进行UrlDecode，会把`SESSDATA`里的%2C全部转译为英文逗号。

唉...我在 [8楼](https://github.com/RayWangQvQ/BiliBiliTool/issues/490#issuecomment-777907085) 就让你们仔细对比下复制出来的Cookie里的`SESSDATA`和`bili_jct`两项...

**Comment by wxyttty** [comment]
然而我是选择后Ctrl+c的
