### ISSUE TITLE
【建议】乱序执行各项任务

### ISSUE THREAD

**Issue by nkh0472** [RayWangQvQ/BiliBiliTool#493]
或许可以减少特征？

**Comment by RayWangQvQ** [comment]
跟我之前想的一样~

但是群里有个朋友的案例很特别，他是之前412后一直没有更新版本进行修复，也就是他每天只调用一个nav接口，跑了一个月，最后还是被监测出来封了7天。。。

我现在的计划是，先从每个接口层面减少特征（尽量做到和浏览器调用一模一样）；
如果这样还是不行，再从调用时间、调用频率、任务顺序这方面考虑；
如果还不行，那就比较麻烦，可能甚至要模仿行为的因果，比如调用投币接口前必须要先调用获取视频接口和观看视频接口（因为实际真实操作不可能在没打开视频的情况下进行投币）。

**Comment by fmcong** [comment]
我建议模拟操作习惯,例如,每天网页登陆B站,先刷几个视频,随机点赞,随机投币(视频数量>点赞>投币)其中随机插领取福利签到之类的任务,这样子的话,会较像是人为操作.

**Comment by RayWangQvQ** [comment]
目前只做了上面说的第一步：从每个接口层面减少特征，但是3月和4月两个月都未再出现警告和封禁的情况。

猜测2种可能：
1. 就是单个接口的特征导致被监测，现在完善后已经解决了风控问题；
2. 二月出现封禁，导致大量人不再使用工具，因为人数变少所以没有再触发风控。
 
暂时先不做其他计划，如果再有问题再做进一步优化。
