### ISSUE TITLE
【建议】请求添加环境变量暂停观看、分享、投币行为而不影响其他任务

### ISSUE THREAD

**Issue by Apocalypsor** [RayWangQvQ/BiliBiliTool#494]
怀疑这些行为会增加账号被识别为刷小号而封号的风险。同时对于6级号也没必要这些经验了。。
例如：
```
IsSkipWatch: true
```

**Comment by RayWangQvQ** [comment]
很棒的建议，下个版本（v1.2.1）会添加。

P.S.投币的配置已经有了，将数量配置为0就行了。

**Comment by Apocalypsor** [comment]
> 很棒的建议，下个版本（v1.2.1）会添加。
> 
> P.S.投币的配置已经有了，将数量配置为0就行了。

对的，这个我看到了，所以我特意没有提`IsSkipCoin`。
非常谢谢大佬！
