### ISSUE TITLE
微信群无法加入，如何在树莓派上运行该程序

### ISSUE THREAD

**Issue by LiuYouheng** [RayWangQvQ/BiliBiliTool#500]
如何在树莓派上运行？是否有指引手册？或者在哪里可以学习到？（我是新手不太懂）如果没有则请再次开放微信群聊，以便交流学习。如果可以请指导一下。谢谢

**Comment by RayWangQvQ** [comment]
已更新

https://github.com/RayWangQvQ/BiliBiliTool/issues/27
