### ISSUE TITLE
service酱turbo自定义的api能有消息，但内容不对。二问：比如如下，部分数字显示是“***”目前没影响使用，但是否正常？

### ISSUE THREAD

**Issue by LiuYouheng** [RayWangQvQ/BiliBiliTool#502]
版本号：v1.2.0
运行环境：Actions

问题描述：
1. 建议添加server酱turbo 据server酱官网，现有支持的server酱版本4月份就不能用了。
**以下是turbo网页信息：**
_API调用实例
最简单的调用方式，直接在浏览器中输入以下 URL：
https://sctapi.ftqq.com/****************.send?title=messagetitle

如果你要发送中文，记得要把参数编码，比如通过 urlencode 函数。这样发送只有标题，如果需要内容，可以这样：
https://sctapi.ftqq.com/****************.send?title=messagetitle&desp=messagecontent

但是需要注意，GET 请求是有长度限制的，所以还是建议大家使用 POST 请求来发送。
API 详细说明
发起推送
向以下 URL 发送一个 HTTP 请求，并传递参数即可。
https://sctapi.ftqq.com/****************.send
参数说明如下：
title: 消息标题，必填。最大长度为 32 。
desp: 消息内容，选填。支持 Markdown语法 ，最大长度为 32KB ,消息卡片截取前 30 显示。
openid: 选填。抄送给其他关注你测试号的 openid ，多个 openid 用 , 隔开。
查询推送状态
调用发起推送接口后，我们并不是立刻调用微信接口，而是会将任务放入异步推送队列。所以返回的结果是放入队列是否成功。
如果想要查询微信发是否成功，请将其返回中的 pushid 和 readkey，发送到以下 URL 查询。
注意 pushid 是用 id 参数传递。
https://sctapi.ftqq.com/push?id={pushid}&readkey={readkey}
返回值中，wxstatus 即为微信接口返回的内容。为空则该任务可能还未执行。
调用函数
PHP
function sc_send(  $text , $desp = '' , $key = '[SENDKEY]'  )
{
    $postdata = http_build_query( array( 'text' => $text, 'desp' => $desp ));
    $opts = array('http' =>
    array(
        'method'  => 'POST',
        'header'  => 'Content-type: application/x-www-form-urlencoded',
        'content' => $postdata));
    
    $context  = stream_context_create($opts);
    return $result = file_get_contents('https://sctapi.ftqq.com/'.$key.'.send', false, $context);

}_

**2. 如下：** 许多数字都显示的***
[***9:***:***5 INF] 版本号：Ray.BiliBiliTool-v***.***.0
[***9:***:***5 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool
[***9:***:***5 INF] 当前环境：Production
[***9:***:***5 INF] 当前IP：5***.***.65.85 

[***9:***:***5 INF] -----开始每日任务-----

[***9:***:***5 INF] 随机休眠9分钟 

[***9:***0:***5 INF] ---开始【登录】---
[***9:***0:*** INF] 登录成功，经验+5 √
[***9:***0:*** INF] 用户名: 杨**L
[***9:***0:*** INF] 硬币余额: ***94.6
[***9:***0:*** INF] 如每日做满65点经验，距离升级到 Lv5 还有: ***7天
[***9:***0:*** INF] ---结束---

[***9:***0:*** INF] ---开始【观看、分享视频】---
[***9:***0:*** INF] 今天已经观看过了，不需要再看啦
[***9:***0:*** INF] 今天已经分享过了，不用再分享啦
[***9:***0:*** INF] ---结束---

[***9:***0:*** INF] ---开始【投币】---
[***9:***0:***8 INF] 今日已投5枚硬币，已完成投币任务，不需要再投啦~
[***9:***0:***8 INF] ---结束---

[***9:***0:***8 INF] ---开始【漫画签到】---
[***9:***0:46 INF] 今日已签到过，无法重复签到
[***9:***0:46 INF] ---结束---

[***9:***0:46 INF] ---开始【直播中心签到】---
[***9:***0:5*** INF] 今日已签到过,无法重复签到
[***9:***0:5*** INF] ---结束---

[***9:***0:5*** INF] ---开始【直播中心银瓜子兑换硬币】---
[***9:***0:5*** INF] 目标兑换日期为***号，今天是***7号，跳过兑换任务
[***9:***0:5*** INF] ---结束---

[***9:***0:5*** INF] ---开始【每月领取大会员福利】---
[***9:***0:5*** INF] 目标领取日期为***号，今天是***7号，跳过领取任务
[***9:***0:5*** INF] ---结束---

[***9:***0:5*** INF] ---开始【每月领取大会员漫画权益】---
[***9:***0:5*** INF] 目标领取日期为***号，今天是***7号，跳过领取任务
[***9:***0:5*** INF] ---结束---

[***9:***0:5*** INF] ---开始【每月使用快过期的B币充电】---
[***9:***0:5*** INF] 目标充电日期为***8号，今天是***7号，跳过充电任务
[***9:***0:5*** INF] ---结束---

[***9:***0:5*** INF] -----全部任务已执行结束-----

[***9:***0:5*** INF] 开始推送
***0***-0***7T***:***0:5***.77***487***Z 开始推送到:自定义
***0***-0***7T***:***0:57.707***68***Z Response status: OK.
***0***-0***7T***:***0:57.707***07***Z Response content: {"code":0,"message":"","data":{"pushid":"407***86","readkey":"SCT0tf6ai***Uj5U***","error":"SUCCESS","errno":0}}.

[***9:***0:57 INF] 正在自动关闭应用...

**Comment by LiuYouheng** [comment]
有些很多**粗体**是误判的，所以有粗体的地方就代表原文是由许多**的地方，是怎么回事？第一次运行的时候没有这个问题  其次，如果不能添加service酱turbo，那请指导一下怎么设置呢

**Comment by fmcong** [comment]
https://sct.ftqq.com/forward   server酱turbo 使用推荐通道,可以完整显示内容,即企业微信应用消息,,,我尝试了一下,测试了使用企业微信应用消息的方式发送,,  通过应用api可以发送长文  32KB  ,
但对于免费版server酱turbo的应用,,微信插件应用显示仅有标题前30中文字符,,需要点击链接进入网页浏览完整,,
server酱turbo  其他推送方式未测试

**Comment by RayWangQvQ** [comment]
暂未测试过server酱turbo版，大概浏览了下介绍，其主要通道是往企业微信推，那建议可以直接在bilibili-tool配置企业微信推送了。

根据目前已经使用的这段时间的经验，server酱并不是推送的首选方案，一是没有微信订阅号推送后就没有明显优势了，二是因为被很多类似羊毛项目调用，导致服务器经常过载挂掉。

后续会考虑维护支持server酱turbo版，如果发现有更好用的集成平台式的推送，也会继续集成为默认推送方案。

P.S.大家如果有好用的推送平台，也可以推荐下。

**Comment by LiuYouheng** [comment]
？？？？？？？？？？？不是，我刚一看，这个程序登录的不是我的账号啊，而且好几天没推送了，我才反应过来？？？
