### ISSUE TITLE
logs 显示不完全

### ISSUE THREAD

**Issue by LiuYouheng** [RayWangQvQ/BiliBiliTool#506]
版本号：1.2.0
运行环境：Actions

问题描述：logs显示不完全

[logs_19.zip](https://github.com/RayWangQvQ/BiliBiliTool/files/6056260/logs_19.zip)
附文件

ps: “3.3.3. SupportUpIds（优先选择支持的up主Id集合）” 最多选择多少位up（有效），如果我添加15个，它是会从前10个找，还是会均匀概率地从这15个里面找？上线是几个？谢谢

**Comment by LiuYouheng** [comment]
[***:11:***7 INF] 版本号：Ray.BiliBiliTool-v1.***.0
[***:11:***7 INF] 开源地址：https://github.com/RayWangQvQ/BiliBiliTool
[***:11:***7 INF] 当前环境：Production
[***:11:***7 INF] 当前IP：40.1***.50.***7 

[***:11:***7 INF] -----开始每日任务-----

[***:11:***7 INF] 随机休眠8分钟 

[***:19:***7 INF] ---开始【登录】---
[***:19:45 INF] 登录成功，经验+5 √
[***:19:45 INF] 用户名: Sup*****at
[***:19:45 INF] 硬币余额: 180.6
[***:19:45 INF] 如每日做满65点经验，距离升级到 Lv5 还有: ***1天
[***:19:45 INF] ---结束---

[***:19:5*** INF] ---开始【观看、分享视频】---
[***:***0:07 INF] 获取随机视频：致敬英雄，我的法医老师，读不出来的尸检报告
[***:***0:07 INF] 今天已经观看过了，不需要再看啦
[***:***0:14 INF] 视频分享成功，经验+5 √
[***:***0:14 INF] ---结束---

[***:***0:14 INF] ---开始【投币】---
[***:***0:*** INF] 今日已投0枚硬币，目标是投***枚，还需再投***枚
[***:***0:***9 INF] 投币前余额为 : 180.6
[***:***1:06 INF] 为“（吃播）跟软软和大胖面基啦！一起吃了本帮菜！还学了上海话和教了德语！”投币成功，经验+10 √
[***:***1:44 INF] 为“【Hiiro/若芖】白日”投币成功，经验+10 √
[***:***:1*** INF] 为“朋友请客吃火锅 我跟老弟狂吃10盘肉 惊呆了”投币成功，经验+10 √
[***:***:***1 INF] 投币任务完成，余额为: 177.6
[***:***:***1 INF] ---结束---

[***:***:***1 INF] ---开始【漫画签到】---
[***:***:***8 INF] 完成漫画签到
[***:***:***8 INF] ---结束---

[***:***:***8 INF] ---开始【直播中心签到】---
[***:***:***6 INF] 直播签到成功，本次签到获得***000点用户经验,***根辣条,
[***:***:***6 INF] ---结束---

[***:***:***6 INF] ---开始【直播中心银瓜子兑换硬币】---
[***:***:4*** INF] 银瓜子兑换硬币成功
[***:***:50 INF] 当前银瓜子余额: 10***096
[***:***:58 INF] 当前硬币余额: 178.6
[***:***:58 INF] ---结束---

[***:***:58 INF] ---开始【每月领取大会员福利】---
[***:***:58 INF] 目标领取日期为***号，今天是***6号，跳过领取任务
[***:***:58 INF] ---结束---

[***:***:58 INF] ---开始【每月领取大会员漫画权益】---
[***:***:58 INF] 目标领取日期为***号，今天是***6号，跳过领取任务
[***:***:58 INF] ---结束---

[***:***:58 INF] ---开始【每月使用快过期的B币充电】---
[***:***:58 INF] 目标充电日期为***8号，今天是***6号，跳过充电任务
[***:***:58 INF] ---结束---

[***:***:58 INF] -----全部任务已执行结束-----

[***:***:58 INF] 开始推送
***0***1-0***6T15:***:58.***90464Z Exception while emitting periodic batch from Ray.Serilog.Sinks.OtherApiBatched.OtherApiBatchedSink: Invalid URI: The format of the URI could not be determined.
[***:***:58 INF] 正在自动关闭应用...

**Comment by LiuYouheng** [comment]
run app 底下的内容有很多缺失

**Comment by RayWangQvQ** [comment]
1.日志没看出有问题；
2.SupportUpIds没有上限；
3.随机取。

**Comment by LiuYouheng** [comment]
run app 里，很多都被*掉了，比如如“每日做满65点经验，距离升级到 Lv5 还有**: ***1天**”

**Comment by RayWangQvQ** [comment]
GitHub Acionts 会把所有与 Secrets 值相同的信息用星号加密，避免暴露隐私数据。

推送出去的内容是完整的。
