### ISSUE TITLE
硬币越来越少了

### ISSUE THREAD

**Issue by like-tb** [RayWangQvQ/BiliBiliTool#513]
建议内容：
（提issue前请确认没有其他人提过相同的，重复提交会被删除，严重的会进行拉黑处理！）
每天只获取到1个币，然后会自动投5个币
![image](https://user-images.githubusercontent.com/69371859/110235723-981a7b80-7f6c-11eb-83d8-4d072996600b.png)

**Comment by like-tb** [comment]
投五个币都能获得经验还是只投一个就行了啊，我等级才lv2，如果都有经验那就没关系，毕竟我看着硬币每天都在变少有点慌

**Comment by like-tb** [comment]
> 建议内容：
> （提issue前请确认没有其他人提过相同的，重复提交会被删除，严重的会进行拉黑处理！）
> 每天只获取到1个币，然后会自动投5个币
> ![image](https://user-images.githubusercontent.com/69371859/110235723-981a7b80-7f6c-11eb-83d8-4d072996600b.png)

**Comment by CHIZI-0618** [comment]
投满5个才能赚满经验，每天1个币是b站的登录奖励
还有，可以自己配置每天投几个币

**Comment by like-tb** [comment]
设置投币数量的任务文件是哪个啊，我去改改
