### ISSUE TITLE
请教大佬，你这个在openwrt的dockerman中怎么运行啊？命令要怎么写？

### ISSUE THREAD

**Issue by caliban511** [RayWangQvQ/BiliBiliTool#514]
如题。
在openwrt的luci-app-dockerman中，要怎么运行啊。
我拉取后，试着按照你给出的信息写运行命令，但无法正常运行。
求教。

docker run -dit \
    -v /opt/bilibili_tool/my_crontab:/app/custom_crontab \
    -v /opt/bilibili_tool/Logs:/app/Logs \
    --network host \
    -e ASPNETCORE_ENVIRONMENT=Production \
    -e Ray_Security__IsSkipDailyTask=false \
    -e Ray_BiliBiliCookie__CookieStr="cookie" \
    -e Ray_Serilog__WriteTo__6__Args__scKey="SCU****" \
    --name bilibili_tool \
    --restart always \
    zai7lou/bilibili_tool

**Comment by snowman32** [comment]
兄弟搞定没这个。。

**Comment by caliban511** [comment]
> 兄弟搞定没这个。。

没有，不会搞。

**Comment by snowman32** [comment]
> > 兄弟搞定没这个。。
> 
> 没有，不会搞。

大兄弟。。我已经搞定了

**Comment by caliban511** [comment]
> > > 兄弟搞定没这个。。
> > 
> > 
> > 没有，不会搞。
> 
> 大兄弟。。我已经搞定了

好吧，恭喜你了。

**Comment by wyUshio** [comment]
> 兄弟搞定没这个。。

求贴个命令 搞不定...

**Comment by RayWangQvQ** [comment]
无法正常运行是指啥？
报错或者日志信息好待贴一些啊。。。

对openwrt不了解，但是有个点需要特别关注下：

v2.0.0之前的镜像，只支持cpu架构为amd64的机器；当前的镜像已同事支持amd64和arm64两种：
![image](https://user-images.githubusercontent.com/31154238/116674271-01e85c00-a9d7-11eb-8249-a158a7dc53ed.png)

如果是因为这个原因，那么现在更新下镜像就可以解决了。

**Comment by bjl101501** [comment]
我也是小白，我是这么安装的。
1.使用winscp连接op，按照大佬的教程创建目录，两个文件放上；
2.op安装docker-compose，dockerman可以先拉取镜像；
3.使用终端cd到目录，然后还是大佬的教程：在当前目录执行启动容器命令：docker-compose up -d
