### ISSUE TITLE
添加pushplus的推送方式

### ISSUE THREAD

**Issue by qq1270735037** [RayWangQvQ/BiliBiliTool#516]
pushplus.hxtrip.com 已经发了相关通知，4月份前后即将关闭 pushplus.hxtrip.com 接口的推送
文章链接： https://mp.weixin.qq.com/s/XbWih4Mv5ggBPGg0-QBJJw

建议域名改为 www.pushplus.plus 以便后续能继续使用推送加的服务

**Comment by RayWangQvQ** [comment]
收到，pushplus的设计挺好的，特别是群发的订阅模式，后面会集成的。

**Comment by drw2005** [comment]
请教，PushPlus如何设置推送？

**Comment by RayWangQvQ** [comment]
文档待会补，稍等

**Comment by RayWangQvQ** [comment]
暂无问题反馈，关闭
