### ISSUE TITLE
【Bug】天选时刻抽奖不会跳过需要舰长的抽奖

### ISSUE THREAD

**Issue by zhihaofans** [RayWangQvQ/BiliBiliTool#519]
版本号：1.2.2
运行环境：Actions

问题描述：天选时刻抽奖碰到需要上舰的抽奖还是提示参与成功了，这是成功参与了还是参与失败但识别错误？跳过上舰抽奖次数多了会不会有被阿b封号可能性

日志信息：(主播信息去掉了)
```
2021-03-15T16:54:14.3969844Z [00:54:14 INF] 开始检查直播间：***(***)
2021-03-15T16:55:00.6521130Z [00:55:00 INF] 奖励：3元，条件：至少成为主播的舰长
2021-03-15T16:55:03.8355104Z [00:55:03 INF] 参与抽奖成功!
```

**Comment by RayWangQvQ** [comment]
1.`成功参与了还是参与失败但识别错误？`
成功参与了。当前判断是否参与抽奖，只由是否需要赠送礼物决定，凡不需要赠送礼物的都会去尝试抽奖。

2.`跳过上舰抽奖次数多了会不会有被阿b封号可能性？`
根据实际使用场景，都是进入直播间后，自动弹出天选抽奖弹窗，然后去点一下抽奖按钮，需要赠送礼物的会提示赠送，不满足条件的会提示不满足，这个场景是没有问题的。
我能想到的可能被检测的风险，不是在这，而是数据异常问题。比如，一个账号都没有观看直播的记录，也没有弹幕或任务其他互动记录，只参与了天选抽奖。阿b想要过滤出这些特征还是比较容易的，就看阿b想不想管。

关于筛选，后面会把筛选条件开放为配置，自己设置哪些参与哪些不参与。
关于安全问题，需要再观察一段时间，如果被警告，要么是尝试优化，要么就直接删掉这个任务算了（因为我发现大家好像并不怎么需要这个功能，出来后挺多人问怎么关掉的）

**Comment by zhihaofans** [comment]
@RayWangQvQ 好的，谢谢解答。这个功能的确不怎么需要，因为天选时刻任务每天只执行一次的话中奖几率渺小，可有可无
