### ISSUE TITLE
【Bug】部分接口返回乱码

### ISSUE THREAD

**Issue by wangkangfeng99** [RayWangQvQ/BiliBiliTool#523]
版本号：bilibili-tool-v1.2.4-linux-x64.zip

运行环境：ubuntu18.04 lts 

问题描述：启动报错

日志信息：

> ubuntu@VM-0-3-ubuntu:~$ cd /home/bilibili-tool-v1.2.4-linux-x64/linux-x64
> ubuntu@VM-0-3-ubuntu:/home/bilibili-tool-v1.2.4-linux-x64/linux-x64$ dotnet Ray.BiliBiliTool.Console.dll
> [14:41:11 INF] 版本号  ：Ray.BiliBiliTool-v1.2.4
> 2021-03-24T06:41:11.5873126Z Caught exception while emitting to sink Serilog.Sinks.File.RollingFileSink: 
> 
> > System.UnauthorizedAccessException: Access to the path '/home/bilibili-tool-v1.2.4-linux-x64/linux-x64/Logs' is denied.
> 
> 
>  ---> System.IO.IOException: Permission denied
>    --- End of inner exception stack trace ---
>    at System.IO.FileSystem.CreateDirectory(String fullPath)
>    at System.IO.Directory.CreateDirectory(String path)
>    at Serilog.Sinks.File.FileSink..ctor(String path, ITextFormatter textFormatter, Nullable`1 fileSizeLimitBytes, Encoding encoding, Boolean buffered, FileLifecycleHooks hooks)
>    at Serilog.Sinks.File.RollingFileSink.OpenFile(DateTime now, Nullable`1 minSequence)
>    at Serilog.Sinks.File.RollingFileSink.AlignCurrentFileTo(DateTime now, Boolean nextSequence)
>    at Serilog.Sinks.File.RollingFileSink.Emit(LogEvent logEvent)
>    at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
> [14:41:13 INF] 当前IP  ：120.53.230.79 
> [14:41:13 INF] 开源地址：github.com/RayWangQvQ/BiliBiliTool 
> 
> [14:41:13 INF] ------开始【每日任务】------
> 
> [14:41:13 INF] ----开始【登录】----
> [14:42:14 ERR] [REQUEST]
> GET /x/web-interface/nav HTTP/1.1
> Referer: https://www.bilibili.com/
> Origin: https://www.bilibili.com
> Host: api.bilibili.com
> Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
> Accept-Encoding: deflate, br
> Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
> Sec-Fetch-Dest: empty
> Sec-Fetch-Mode: cors
> Sec-Fetch-Site: same-site
> Connection: keep-alive
> 
> [RESPONSE]
> HTTP/1.1 200 OK
> Date: Wed, 24 Mar 2021 06:42:13 GMT
> Transfer-Encoding: chunked
> Connection: keep-alive
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Methods: GET,POST
> Access-Control-Allow-Origin: https://www.bilibili.com
> Bili-Status-Code: 0
> Bili-Trace-Id: 3e1027bdac605adf
> Vary: Origin
> Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip
> Access-Control-Expose-Headers: X-Cache-Webcdn
> Set-Cookie: bfe_id=6f285c892d9d3c1f8f020adad8bed553; Path=/; Max-Age=600; Expires=Wed, 24-Mar-21 06:52:13 GMT
> Cache-Control: no-cache
> X-Cache-Webcdn: BYPASS from ks-zjnb-dx-w-02
> Content-Type: application/json; charset=utf-8
> Expires: Wed, 24 Mar 2021 06:42:12 GMT
> Content-Encoding: br
> Content-Length: 538
> 
> oc0�Ӝ*�f7�)���[��QJ��f���.6½�F�^j���JU8$��`��6�#�T4�Ko�oȢ1�'P�@�B�S����.+Pcdm�b��       ���
>                         ,�+����D���m?����#鸡�=G����kK����PQcXjsO�"�US�ɲ�����R��G@G;��jYex��]i`�``BY�����u�AH)r����B�p
> %�w��q����^��u�N��V����&�F{�y8d���@�/��J�)a&����������i�}=?�����PH/2�r6��                                            ����u9�b
> k���"{>T���\ʦk�>bA�$�H5�>����gE���pv�&�gmDq#�s/Cل��W�ͤ�9 #(m��6� ����V-$4̰�k8��'����tj
> 
> [EXCEPTION]
> System.Text.Json.JsonException: '!' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
>  ---> System.Text.Json.JsonReaderException: '!' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
>    at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
>    at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
>    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
>    at System.Text.Json.Utf8JsonReader.Read()
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
>    at WebApiClientCore.ApiResponseContextExtensions.JsonDeserializeAsync(ApiResponseContext context, Type objType)
>    at WebApiClientCore.Attributes.JsonReturnAttribute.SetResultAsync(ApiResponseContext context)
>    at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
>    at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)
> 
> [ELAPSED] 00:01:00.7246983
> [14:42:14 ERR] 程序发生异常：'!' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
> [14:42:14 ERR] 程序发生异常：'!' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
> [14:42:14 ERR] 程序异常终止，原因：'!' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
> [14:42:14 INF] 开始推送
> 2021-03-24T06:42:14.0374947Z 开始推送到:Server酱
> 2021-03-24T06:42:14.3696589Z Response status: OK.
> 2021-03-24T06:42:14.3705724Z Response content: {"errno":0,"errmsg":"success","dataset":"done"}.
> 
> [14:42:14 INF] 正在自动关闭应用...
> [14:42:14 FTL] Host terminated unexpectedly!
> System.Net.Http.HttpRequestException: '!' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
>  ---> System.Text.Json.JsonException: '!' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
>  ---> System.Text.Json.JsonReaderException: '!' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
>    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
>    at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
>    at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
>    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
>    at System.Text.Json.Utf8JsonReader.Read()
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    --- End of inner exception stack trace ---
>    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
>    at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
>    at WebApiClientCore.ApiResponseContextExtensions.JsonDeserializeAsync(ApiResponseContext context, Type objType)
>    at WebApiClientCore.Attributes.JsonReturnAttribute.SetResultAsync(ApiResponseContext context)
>    at WebApiClientCore.Attributes.ApiReturnAttribute.OnResponseAsync(ApiResponseContext context)
>    at WebApiClientCore.Implementations.ApiRequestExecuter.HandleResponseAsync(ApiResponseContext context)
>    at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
>    at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
>    --- End of inner exception stack trace ---
>    at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
>    at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 45
>    at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
>    at Ray.BiliBiliTool.Application.DailyTaskAppService.DoTask()
>    at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
>    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
>    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
>    at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /home/runner/work/BiliBiliTool/BiliBiliTool/src/Ray.BiliBiliTool.Console/Program.cs:line 25
>

**Comment by RayWangQvQ** [comment]
如日志所示，有两个异常：

1.日志文件（/home/bilibili-tool-v1.2.4-linux-x64/linux-x64/Logs）没有权限

2.接口返回乱码

这里只讨论异常2乱码问题，原因是`Content-Encoding: br`，应该是接口发生了变更，返回内容改成了压缩格式。

稍后会进行排查和兼容，于下一版本修复。

**Comment by wangkangfeng99** [comment]
那日志文件没有权限怎么解决？找不到那个文件夹

**Comment by wangkangfeng99** [comment]
更新后使用正常
