### ISSUE TITLE
有些配置不能通过环境变量来处理？

### ISSUE THREAD

**Issue by chenmg2020** [RayWangQvQ/BiliBiliTool#526]
例如：
意义 | 每月几号自动充电
值域 | [-1,31]，-1表示不指定，默认月底最后一天；0表示不充电
默认值 | -1
环境变量示范 |  
命令行示范 | -dayOfAutoCharge=25
GitHub Secrets 示范 | Name:DAYOFAUTOCHARGE Value: 25

类似这种不能通过环境变量配置吗？

**Comment by RayWangQvQ** [comment]
所有配置项都可以通过环境变量来配置。

文档里有些省缺了，是因为我没有来得及补上。

个人最近比较忙，如果有朋友时间充裕，欢迎提交PR来帮忙补充。

规则参考已有配置应该很容易推出来：以`Ray_`开口，然后根据appsetting.json里的json层级，用双下划线分隔。
