### ISSUE TITLE
【Bug】获取ip为空

### ISSUE THREAD

**Issue by chenmg2020** [RayWangQvQ/BiliBiliTool#529]
昨天还好好的，今天发现bilibili_tool    | [15:14:18 INF] 当前IP  ：null 
使用docker-compose
不清楚啥原因，麻烦大佬帮忙看下，感谢

运行信息如下：

bilibili_tool    | 初始启动容器，尝试首次运行每日任务
bilibili_tool    | [15:13:57 INF] 版本号  ：Ray.BiliBiliTool-v1.2.5
bilibili_tool    | [15:14:18 INF] 当前IP  ：null 
bilibili_tool    | [15:14:18 INF] 开源地址：github.com/RayWangQvQ/BiliBiliTool 
bilibili_tool    | 
bilibili_tool    | [15:14:18 INF] 随机休眠2分钟 
bilibili_tool    | 
bilibili_tool    | [15:16:18 INF] -----开始【每日任务】-----
bilibili_tool    | 
bilibili_tool    | [15:16:18 INF] ---开始【登录】---
bilibili_tool    | [15:17:22 ERR] [REQUEST]
bilibili_tool    | GET /x/web-interface/nav HTTP/1.1
bilibili_tool    | Referer: https://www.bilibili.com/
bilibili_tool    | Origin: https://www.bilibili.com
bilibili_tool    | Host: api.bilibili.com
bilibili_tool    | Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
bilibili_tool    | Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
bilibili_tool    | Sec-Fetch-Dest: empty
bilibili_tool    | Sec-Fetch-Mode: cors
bilibili_tool    | Sec-Fetch-Site: same-site
bilibili_tool    | Connection: keep-alive
bilibili_tool    | 
bilibili_tool    | [EXCEPTION]
bilibili_tool    | System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.bilibili.com:443)
bilibili_tool    |  ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
bilibili_tool    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
bilibili_tool    |    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
bilibili_tool    |    --- End of inner exception stack trace ---
bilibili_tool    |    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
bilibili_tool    |    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
bilibili_tool    |    at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
bilibili_tool    |    at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
bilibili_tool    |    at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 30
bilibili_tool    |    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
bilibili_tool    |    at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
bilibili_tool    |    at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)
bilibili_tool    | 
bilibili_tool    | [ELAPSED] 00:01:04.0803148
bilibili_tool    | [15:17:22 ERR] 程序发生异常：Resource temporarily unavailable (api.bilibili.com:443)
bilibili_tool    | [15:17:22 ERR] 程序发生异常：Resource temporarily unavailable (api.bilibili.com:443)
bilibili_tool    | [15:17:22 ERR] 程序异常终止，原因：Resource temporarily unavailable (api.bilibili.com:443)
bilibili_tool    | [15:17:22 INF] 开始推送
bilibili_tool    | 2021-03-26T07:17:22.2979957Z 开始推送到:钉钉
bilibili_tool    | 2021-03-26T07:17:42.5091805Z Exception while emitting periodic batch from Ray.Serilog.Sinks.DingTalkBatched.DingTalkBatchedSink: Resource temporarily unavailable (oapi.dingtalk.com:443)
bilibili_tool    | 2021-03-26T07:17:42.5097841Z 开始推送到:Server酱
bilibili_tool    | 2021-03-26T07:18:02.5349894Z Exception while emitting periodic batch from Ray.Serilog.Sinks.ServerChanBatched.ServerChanBatchedSink: Resource temporarily unavailable (sc.ftqq.com:80)
bilibili_tool    | [15:18:02 INF] 正在自动关闭应用...
bilibili_tool    | [15:18:02 FTL] Host terminated unexpectedly!

**Comment by RayWangQvQ** [comment]
网络有问题吧，下面调用b站api和推送消息也都失败了（都跟网络相关）

**Comment by chenmg2020** [comment]
> 网络有问题吧，下面调用b站api和推送消息也都失败了（都跟网络相关）

我也觉得是网络问题，但是其他东西使用都没问题，奇怪了，我再查一下
