### ISSUE TITLE
希望能够手动配置是否显示IP信息

### ISSUE THREAD

**Issue by davidelectricfree** [RayWangQvQ/BiliBiliTool#534]
希望能够手动配置是否在推送信息显示完整的IP信息，因为使用了第三方的推送，看能不能在推送的明文信息里面，把IP不全部显示，打码某几位。十分感谢。
` _logger.LogInformation("【当前IP】：{ip} ", IpHelper.GetIp());`

**Comment by RayWangQvQ** [comment]
可否描述下，为什么会有这样的需求？

**Comment by davidelectricfree** [comment]
> 可否描述下，为什么会有这样的需求？是担心暴露给第三方推送平台的意思吗？

可能算是我个人的需求，其他人可能没这个需求，我这边已经把那个语句屏蔽，重新编译了，问题已经解决，十分感谢。

**Comment by RayWangQvQ** [comment]
嗯既然已经通过api调用了推送平台，ip应该已经被平台捕捉到了，加密好像没什么意义。

**Comment by davidelectricfree** [comment]
> 嗯既然已经通过api调用了推送平台，ip应该已经被平台捕捉到了，加密好像没什么意义。

问题是有些平台的推送账号（如QQ）是公共账号，这种公共香港并不是只有平台知道账号密码。
