### ISSUE TITLE
【Bug】老哥，石锤了，偶尔会出现获取ip为null问题

### ISSUE THREAD

**Issue by chenmg2020** [RayWangQvQ/BiliBiliTool#536]
版本号：v1.2.5
运行环境：虚拟机：Linux

问题描述：使用docker-compose运行，偶尔会出现获取ip为null问题，实际上网络并无问题，不清楚啥原因

日志信息：
bilibili_tool    | 初始启动容器，尝试首次运行每日任务
bilibili_tool    | [10:40:34 INF] 版本号  ：Ray.BiliBiliTool-v1.2.5
bilibili_tool    | [10:40:54 INF] 当前IP  ：null 
bilibili_tool    | [10:40:54 INF] 开源地址：github.com/RayWangQvQ/BiliBiliTool 
bilibili_tool    | 
bilibili_tool    | [10:40:54 INF] 随机休眠3分钟 
bilibili_tool    | 
bilibili_tool    | [10:43:54 INF] -----开始【每日任务】-----
bilibili_tool    | 
bilibili_tool    | [10:43:54 INF] ---开始【登录】---
bilibili_tool    | [10:45:06 ERR] [REQUEST]
bilibili_tool    | GET /x/web-interface/nav HTTP/1.1
bilibili_tool    | Referer: https://www.bilibili.com/
bilibili_tool    | Origin: https://www.bilibili.com
bilibili_tool    | Host: api.bilibili.com
bilibili_tool    | Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
bilibili_tool    | Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
bilibili_tool    | Sec-Fetch-Dest: empty
bilibili_tool    | Sec-Fetch-Mode: cors
bilibili_tool    | Sec-Fetch-Site: same-site
bilibili_tool    | Connection: keep-alive
bilibili_tool    | 
bilibili_tool    | [EXCEPTION]
bilibili_tool    | System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.bilibili.com:443)
bilibili_tool    |  ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
bilibili_tool    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
bilibili_tool    |    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
bilibili_tool    |    --- End of inner exception stack trace ---
bilibili_tool    |    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
bilibili_tool    |    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
bilibili_tool    |    at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
bilibili_tool    |    at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
bilibili_tool    |    at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 30
bilibili_tool    |    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
bilibili_tool    |    at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
bilibili_tool    |    at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)
bilibili_tool    | 
bilibili_tool    | [ELAPSED] 00:01:12.0759374
bilibili_tool    | [10:45:06 ERR] 程序发生异常：Resource temporarily unavailable (api.bilibili.com:443)
bilibili_tool    | [10:45:06 ERR] 程序发生异常：Resource temporarily unavailable (api.bilibili.com:443)
bilibili_tool    | [10:45:06 ERR] 程序异常终止，原因：Resource temporarily unavailable (api.bilibili.com:443)
bilibili_tool    | [10:45:06 INF] 开始推送
bilibili_tool    | 2021-03-31T02:45:06.5450122Z 开始推送到:钉钉
bilibili_tool    | 2021-03-31T02:45:26.6410349Z Exception while emitting periodic batch from Ray.Serilog.Sinks.DingTalkBatched.DingTalkBatchedSink: Resource temporarily unavailable (oapi.dingtalk.com:443)
bilibili_tool    | 2021-03-31T02:45:26.6415726Z 开始推送到:Server酱
bilibili_tool    | 2021-03-31T02:45:46.6660674Z Exception while emitting periodic batch from Ray.Serilog.Sinks.ServerChanBatched.ServerChanBatchedSink: Resource temporarily unavailable (sc.ftqq.com:80)
bilibili_tool    | [10:45:46 INF] 正在自动关闭应用...
bilibili_tool    | [10:45:46 FTL] Host terminated unexpectedly!
bilibili_tool    | System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.bilibili.com:443)
bilibili_tool    |  ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
bilibili_tool    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
bilibili_tool    |    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
bilibili_tool    |    --- End of inner exception stack trace ---
bilibili_tool    |    at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
bilibili_tool    |    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
bilibili_tool    |    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
bilibili_tool    |    at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
bilibili_tool    |    at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
bilibili_tool    |    at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 30
bilibili_tool    |    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
bilibili_tool    |    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
bilibili_tool    |    at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
bilibili_tool    |    at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)
bilibili_tool    |    at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(ApiRequestContext request)
bilibili_tool    |    at WebApiClientCore.Implementations.DefaultApiActionInvoker`1.InvokeAsync(HttpClientContext context, Object[] arguments)
bilibili_tool    |    at Ray.BiliBiliTool.DomainService.AccountDomainService.LoginByCookie() in /src/Ray.BiliBiliTool.DomainService/AccountDomainService.cs:line 45
bilibili_tool    |    at Ray.BiliBiliTool.Application.DailyTaskAppService.Login()
bilibili_tool    |    at Ray.BiliBiliTool.Application.DailyTaskAppService.DoTask()
bilibili_tool    |    at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 65
bilibili_tool    |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
bilibili_tool    |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
bilibili_tool    |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
bilibili_tool    |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
bilibili_tool    |    at Ray.BiliBiliTool.Console.Program.Main(String[] args) in /src/Ray.BiliBiliTool.Console/Program.cs:line 25
bilibili_tool    | 配置cron定时任务
bilibili_tool    | 检测到自定义了cron定时任务，使用自定义配置
bilibili_tool    | 导入环境变量
bilibili_tool    | 启动定时任务，开启每日定时运行

不会只有我出现这种问题吧，不会吧（dog）~

**Comment by RayWangQvQ** [comment]
你这不是ip问题了，下面访问b站/x/web-interface/nav接口也异常了，推送也异常了。

请先确保网络通畅。

**Comment by chenmg2020** [comment]
> 你这不是ip问题了，下面访问b站/x/web-interface/nav接口也异常了，推送也异常了。
> 
> 请先确保网络通畅。

非常奇怪，我的网络确实是通畅的，甚至可以下载其他东西，只有使用这个才会这样

**Comment by RayWangQvQ** [comment]
什么环境下的docker啊？win下的？还是虚拟机里又装的docker？

**Comment by chenmg2020** [comment]
> 什么环境下的docker啊？win下的？还是虚拟机里又装的docker？

虚拟机里装的docker，但是虚拟机里更新软件包或者拉取拉取镜像这些都没问题，网络是通畅的

**Comment by chenmg2020** [comment]
> 什么环境下的docker啊？win下的？还是虚拟机里又装的docker？

虚拟机里装的docker，但是虚拟机里更新软件包或者拉取拉取镜像这些都没问题，网络是通畅的

**Comment by chenmg2020** [comment]
> 什么环境下的docker啊？win下的？还是虚拟机里又装的docker？

虚拟机里装的docker，但是虚拟机里更新软件包或者拉取拉取镜像这些都没问题，网络是通畅的

**Comment by RayWangQvQ** [comment]
我在win10下的docker没有出现过类似问题，如果是win10的话，建议直接用docker，不用再套一层虚拟机了。

目前没有想出问题，后续可以再继续跟进观察。

**Comment by RayWangQvQ** [comment]
无跟进，关闭
