### ISSUE TITLE
为什么运行Ray.BiliBiliTool.Console.exe 闪了一下就没了

### ISSUE THREAD

**Issue by clown789** [RayWangQvQ/BiliBiliTool#539]

**Comment by RayWangQvQ** [comment]
异常了，详细日志信息在Logs文件夹下看，估计是Cookie没配或配的不对。

在exe所在目录使用命令执行`Ray.BiliBiliTool.Console.exe`，可以使窗口一直保持，不会关闭。

下个版本会优化下，异常时不关闭console窗口。

**Comment by clown789** [comment]
谢谢大佬，等您的下个版本

**Comment by RayWangQvQ** [comment]
已发布
