### ISSUE TITLE
今天未投币，手动运行提示已投币，未能触发投币行为

### ISSUE THREAD

**Issue by PuRonglong** [RayWangQvQ/BiliBiliTool#54]
![image](https://user-images.githubusercontent.com/8725006/99204599-2669c680-27f1-11eb-8339-584b1d17e32b.png)
![image](https://user-images.githubusercontent.com/8725006/99204653-4c8f6680-27f1-11eb-90a7-7cbf49c1e9d8.png)

昨天第一天安装运行成功了，今天不想等到14:10分，就在早上9点过后修改自动运行时间早上8点10分，然后手动运行run all job，结果提示今天已经投币了，然后去B站用户中心查看发现没有投币。这会是什么原因呢，难道三条配置要当天的才能触发吗？

**Comment by gejiawei007** [comment]
这个是B站的问题，去https://account.bilibili.com/account/coin网址看你的硬币记录就好了

**Comment by PuRonglong** [comment]
> 这个是B站的问题，去https://account.bilibili.com/account/coin 网址看你的硬币记录就好了

我第一张图就是这里看的硬币记录

**Comment by PuRonglong** [comment]
我刚才去看了下，有个日志，push修改时间的操作触发了workflow（为什么我当时看不到这次日志），而时间是在9:30
![image](https://user-images.githubusercontent.com/8725006/99229149-98a9cd80-2828-11eb-8629-cef100168ae5.png)
那为什么我9:44分的时候看B站的这个投币硬币记录还是0呢
不太明白，但确实是B站的问题，至于什么问题就不知道了，程序没问题的
