### ISSUE TITLE
天选抽奖任务有没有办法自定义运行频率

### ISSUE THREAD

**Issue by luohan-qiu** [RayWangQvQ/BiliBiliTool#543]
请问天选抽奖能否一日运行多次，如何修改，是修改github/workflows里面的文件吗？谢谢

**Comment by RayWangQvQ** [comment]
Docker可以通过编辑cron，实现自定义运行频率。

GitHub Actions的话，修改 workflow 文件是肯定可以实现的，但是这样就和自动更新冲突了，因为强制拉取上游后，workflow 文件又会被改回去。

这也是一直困扰我的一个问题：即 GitHub Actions 的触发条件是写在工作流脚本里的，而不是像云函数一样作为配置独立在外面的。

之前的每日任务，通过GitHub Environment的延迟实现了自定义触发时间。但是这种只适用于每天只执行一次的任务，像天选这种频率也要自定义，就没办法了。

**目前还没有想到最优的解决办法，如果有有思路的朋友欢迎提供建议。**

**Comment by luohan-qiu** [comment]
请问是修改workflow文件里面什么参数，我不嫌麻烦每次更新后都我都可以手动修改，麻烦告知，谢谢

**Comment by RayWangQvQ** [comment]
如 #552 ，每天只运行1次都被GitHub禁用了Actions功能，所以以后不考虑支持actions了，推荐使用docker运行。
