### ISSUE TITLE
【Bug】为什么，到点后不自动启动呀？

### ISSUE THREAD

**Issue by HopeLight** [RayWangQvQ/BiliBiliTool#545]
版本号：最新版
运行环境：Action

问题描述：发现，设置到点后，整点却没执行

日志信息：发现完全没有运行

**Comment by RayWangQvQ** [comment]
没懂

**Comment by RayWangQvQ** [comment]
另外，议题标题和描述写的不清晰，未贴日志信息，均不符合议题提交规范。
另一个你提的 #542 也存在同样的问题。

提交无意义的议题会扰乱议题环境，请斟酌后提交。

**Comment by RayWangQvQ** [comment]
暂无跟进，关闭
