### ISSUE TITLE
【Bug】请在标题中清晰地概述你要反馈的异常或缺陷

### ISSUE THREAD

**Issue by HanHan233** [RayWangQvQ/BiliBiliTool#548]
版本号：刚刚Fork的，绝对是最新
![image](https://user-images.githubusercontent.com/64469437/114306933-1b9d2e80-9b10-11eb-889c-e6581cfe58cb.png)

运行环境：GitHub Actions
问题描述：
设置了COOKIE但是仍然显示未设置
日志信息：
![image](https://user-images.githubusercontent.com/64469437/114306867-de38a100-9b0f-11eb-9002-c0be135e6131.png)

![image](https://user-images.githubusercontent.com/64469437/114306793-9154ca80-9b0f-11eb-8b77-d3cc2afe8cc5.png)
https://github.com/HanHan233/BiliBiliTool/runs/2317416867?check_suite_focus=true

**Comment by RayWangQvQ** [comment]
![image](https://user-images.githubusercontent.com/31154238/114311013-8efa6c80-9b1f-11eb-9d1d-ef67c2208b82.png)
