### ISSUE TITLE
【Bug】日本語字库缺失

### ISSUE THREAD

**Issue by RA1NO3O** [RayWangQvQ/BiliBiliTool#560]
版本号：2.0.0
运行环境：Windows Server 2019

问题描述：
![image](https://user-images.githubusercontent.com/25654559/115727609-56c41b00-a3b6-11eb-9deb-7244774376a2.png)
レエイン

日志信息：🈚

**Comment by RayWangQvQ** [comment]
其实汉字也缺，是故意加密了名字的中间部分。

**Comment by RA1NO3O** [comment]
> 其实汉字也缺，是故意加密了名字的中间部分。

啊这是刻意的啊，那我关了（无慈悲
