### ISSUE TITLE
【Bug】钉钉机器人推送报错

### ISSUE THREAD

**Issue by hienao** [RayWangQvQ/BiliBiliTool#566]
版本号：最新版本
运行环境：Actions

问题描述：钉钉推送机器人消息提示 ，怀疑是加签 参数没配置导致

日志信息：Response content: {"errcode":310000,"errmsg":"sign not match, more: [https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq]"}.

**Comment by xuxiaohu6** [comment]
我的也是~~~

**Comment by RayWangQvQ** [comment]
钉钉安全策略选“关键字”，当前不支持“加签”。

关键字推荐：`Ray`、`BiliBili`、或任何一定会在日志种出现的文字

关键字只是用于过滤，配置之一即可
