### ISSUE TITLE
【Bug】云函数调用失败  Invoking task timed out after 3 seconds","statusCode":433

### ISSUE THREAD

**Issue by Owen-sqy** [RayWangQvQ/BiliBiliTool#573]
版本号：v2.0.1

运行环境：腾讯云函数

问题描述：使用云函数测试时出现调用失败，任务超时

日志信息：ERROR RequestId:52f8ae4f-53b4-48fd-b130-f274c5558b69 Result:{"errorCode":-1,"errorMessage":"Invoking task timed out after 3 seconds","statusCode":433}

目前解决办法：将配置环境中 初始化超时时间 和 执行超时时间 设为最大值

![image](https://user-images.githubusercontent.com/45102260/117427218-65363900-af57-11eb-8b69-09682dc72519.png)

**Comment by RayWangQvQ** [comment]
嗯需要配置“执行超时时间”，稍后会更新文档，感谢反馈。

**Comment by 8621** [comment]
感谢老哥的提示，给你大大的赞。

**Comment by XZ1314XZ** [comment]
有用，解决了问题

**Comment by iMyLC** [comment]
> 嗯需要配置“执行超时时间”，稍后会更新文档，感谢反馈。

老哥，每次签到完成后推送至server酱Turbo版的函数表达式是什么
