### ISSUE TITLE
【其他】docker部署如何设置TG推送

### ISSUE THREAD

**Issue by maxduke** [RayWangQvQ/BiliBiliTool#579]
你好TG推送章节里面没有环境变量的例子，请问TG推送的环境变量是什么，想在docker-compose里面配置。谢谢

**Comment by RayWangQvQ** [comment]
**所有的配置**都能通过配置文件、环境变量和命令行参数，其中任意1种或多种配合来实现。

配置的本质就是很多个key、value键值对， json 置文件就是有层级的key、value对，而环境变量其实就是把 json 配置文件按层级拉平成key、value对（按层级使用`__`分隔，前缀固定`Ray_`）。

它们本质是同一个东西。

**Comment by maxduke** [comment]
成功了，多谢

**Comment by a-little-cat** [comment]
您好,配置文档里,推送模块的配置key和环境变量基本都是空的,可否补充上..
https://github.com/RayWangQvQ/BiliBiliTool/blob/main/docs/configuration.md#36-%E6%8E%A8%E9%80%81%E7%9B%B8%E5%85%B3
