### ISSUE TITLE
Process completed with exit code 134？

### ISSUE THREAD

**Issue by antsman9** [RayWangQvQ/BiliBiliTool#6]
![image](https://user-images.githubusercontent.com/38621428/98456868-ab832900-21bc-11eb-88b9-2412a996cd09.png)
Secrets 更新过了，没有保存上么？

**Comment by RayWangQvQ** [comment]
1.首先确认Secrets是否添加了3个，而不是一个（每个Cookie对应一个Secret）；

2.然后确认是否USERID和BILIJCT两个Secret是否保存成功空值了（Secrets为了保密，G站把它设置成是不可编辑的，只能重置。也就是添加后，点击编辑进入，value文本框会置空，此时应该填入完整的值再点击保存，直接点击保存会保存成空值）

**Comment by imldy** [comment]
看看的我的pull request能不能解决你的问题 #10

**Comment by antsman9** [comment]
感恩 ~原来是Secrets 的name 错误了。。。。。现在已经好了！
