### ISSUE TITLE
actions版本，微信推送key在哪填？

### ISSUE THREAD

**Issue by zhhenwj** [RayWangQvQ/BiliBiliTool#7]
actions版本，微信推送key在哪填？

**Comment by RayWangQvQ** [comment]
使用GitHub Actions，除了三个必填的Cookie是每个对应一个Secret，其他的所有配置都可以通过添加名为“OTHERCONFIGS”的Secret的实现，其值为多个配置的拼接。

比如，配置微信推送的SCKEY：
Secret Key：`OTHERCONFIGS`
Secret Value：`-pushScKey=123456`

如果有多个，比如既要配微信推送，又要配置优先投币的up主，往后拼接即可：
Secret Key：`OTHERCONFIGS`
Secret Value：`-pushScKey=123456 -supportUpIds=123,456`

这个Value会拼接到启动的命令行之后，作为命令行参数传入程序当中。

**Comment by zhhenwj** [comment]
谢谢，已经解决了
