### ISSUE TITLE
【需求】win版执行成功后自动关闭窗口

### ISSUE THREAD

**Issue by zdxonline** [RayWangQvQ/BiliBiliTool#70]
![image](https://user-images.githubusercontent.com/35787026/99862184-bc2b9a00-2bd3-11eb-9ce8-e92cde6f2664.png)

我在win的自动任务里加入了每天自动签到，但是执行完成后会有这个窗口

建议签到完成后直接关闭窗口或者可以增加执行参数，在完成后关闭窗口。

**Comment by yinghualuowu** [comment]
```
//如果配置了“1”就立即关闭，否则保持窗口以便查看日志信息
if (RayConfiguration.Root["CloseConsoleWhenEnd"] == "1") return;
```
我记得是有参数配置的，试一试CloseConsoleWhenEnd这个吧

**Comment by zdxonline** [comment]
> ```
> //如果配置了“1”就立即关闭，否则保持窗口以便查看日志信息
> if (RayConfiguration.Root["CloseConsoleWhenEnd"] == "1") return;
> ```
> 
> 我记得是有参数配置的，试一试CloseConsoleWhenEnd这个吧

解决了，谢谢
