### ISSUE TITLE
投币数问题

### ISSUE THREAD

**Issue by Vergissmeinnichts** [RayWangQvQ/BiliBiliTool#73]
投币数只能是5吗?我把投币数改成0、1、2都会导致运行出错（修改appsettings.json和添加Secrets都不行），改回5之后又可以正常运行了。

> 10 [12:02:18 INF] -----开始每日任务-----
11
12 [12:02:18 INF] ---开始【登录】---
13 [12:02:19 FTL] 程序发生异常：One or more errors occurred. (Response status code does not indicate success: 412 (Precondition Failed).)

**Comment by RayWangQvQ** [comment]
和投币数量应该没有关系，当前版本（V1.0.10）已将UA开放为配置，用于暂时解决412问题，详情见[常见问题4](https://github.com/RayWangQvQ/BiliBiliTool.Docs/blob/main/questions.md)。
建议更新后，再次修改投币数量试试看。

**Comment by Vergissmeinnichts** [comment]
更新以后解决了,谢谢!

**Comment by RayWangQvQ** [comment]
同 #61
