### ISSUE TITLE
412错误的原因

### ISSUE THREAD

**Issue by zerokos** [RayWangQvQ/BiliBiliTool#77]
412错误是因为UA的设置，隔壁提供了修改UA选项， @RayWangQvQ 大大可以参考下

**Comment by zerokos** [comment]
[https://github.com/JunzhouLiu/BILIBILI-HELPER/issues/110](url)

**Comment by RayWangQvQ** [comment]
感谢提醒，这个大佬也在群里，已经沟通过了。
当前版本（V1.0.10）已将UA开放为配置，用于暂时解决412问题。

**Comment by RayWangQvQ** [comment]
因为已经有人在 #61 提了，这条就加先关了。
