### ISSUE TITLE
我是作者，进来的朋友谁能来告诉我下，你们都是从哪里过来的？

### ISSUE THREAD

**Issue by RayWangQvQ** [RayWangQvQ/BiliBiliTool#8]
为啥今天（2020/11/8）早上突然多了这么多fork？
受宠若惊啊😺

**Comment by wangmanv2** [comment]
在 52pojie 看到的

**Comment by happy888888** [comment]
Insights -> Traffic 选项卡里是能看到github游客来源的，看看就知道了

什么时候B站签到这么火了，这么多大佬都来做这个，我自己的B站签到脚本fork都涨得很慢，可能java写的比较受欢迎一些

**Comment by antsman9** [comment]
https://www.52pojie.cn/forum.php?mod=viewthread&tid=1299101&highlight=B

**Comment by RayWangQvQ** [comment]
原来是被发到 52pojie 了，顺便问下有没有大佬有邀请码，我也去注册个

**Comment by orgailo** [comment]
> 原来是被发到52pojie了，顺便问下有没有大佬有邀请码，我也去注册个

11号当天开放注册，顺便问一下为什么只有源码了？没有直接运行文件了吗？

**Comment by happy888888** [comment]
开放注册时间`2020年11月11日  12：00 -- 14：00 和  20：00 -- 22：00` 到时候可以注册

**Comment by RayWangQvQ** [comment]
@orgailo 最近发版太快了，有的版本就没来得及打包上传（源码包是GitHub自动生成的）。
今晚会再发一个版本，作为长期支持版，顺带会上传打包文件。

**Comment by RayWangQvQ** [comment]
> Insights -> Traffic 选项卡里是能看到github游客来源的，看看就知道了
> 
> 什么时候B站签到这么火了，这么多大佬都来做这个，我自己的B站签到脚本fork都涨得很慢，可能java写的比较受欢迎一些

其实应用内容没啥东西，主要是想借这个应用试着用DDD领域驱动搭出一个框架，以后写类似的任务脚本工具都可以根据这个框架来写。
这次开发还是总结出不少经验的（主要是踩坑多），比如调用接口可以用Refit或者其他组件映射为强类型的Interface，这样后期会比较好做AOP，比如应该尽可能多的将功能开放成配置，比如日志输出端的解耦等等。
你的fork已经很多了，看来又是一个大佬👍
我这个是.Net Core的版本，确实还是Java的会比较收欢迎的。

**Comment by harperol** [comment]
大佬，有个疑问，今天运行结果自动投了9个币，设置里是默认的5个币，是出bug了吗？

**Comment by RayWangQvQ** [comment]
> 大佬，有个疑问，今天运行结果自动投了9个币，设置里是默认的5个币，是出bug了吗？

看了你的日志，如下：
![image](https://user-images.githubusercontent.com/31154238/98465181-6b469980-2202-11eb-8ca3-79ae4eb68e37.png)

我猜测是因为你同时跑了两个work flow，第一个和第二个的投币时间有重叠，也就是：
跑第一个程序时，运行到投币任务，计算出需要投币5次，并且开始投币。
在第一个程序刚投完第1个币时，第二个程序刚好也跑到了投币任务，并且第二个程序发现今天已经投了1个币（刚才第一个程序投的），所以第二个程序开始计划投4个币。。。
最后的结果就是，第一个程序投了5个，第二个程序投了4个，加起来一共9个。

### 我是万万没想到，我写个单个用户使用的工具类软件，你竟然给我测出了高并发的Bug哈哈哈哈哈**

目前正常使用不会出现这种bug的，可以放心先用着。
具体怎么解决（或者说需不需要解决）这种因为多开软件而引起的bug，后面我再考虑下，毕竟这个程序的目的本就是给一个人一天用一次而已。

感谢反馈，朋友你太厉害了，你才是大佬，不做测试工程师是测试界的一大损失！

**Comment by JunzhouLiu** [comment]
> > 大佬，有个疑问，今天运行结果自动投了9个币，设置里是默认的5个币，是出bug了吗？
> 
> 看了你的日志，如下：
> ![image](https://user-images.githubusercontent.com/31154238/98465181-6b469980-2202-11eb-8ca3-79ae4eb68e37.png)
> 
> 我猜测是因为你同时跑了两个work flow，第一个和第二个的投币时间有重叠，也就是：
> 跑第一个程序时，运行到投币任务，计算出需要投币5次，并且开始投币。
> 在第一个程序刚投完第1个币时，第二个程序刚好也跑到了投币任务，并且第二个程序发现今天已经投了1个币（刚才第一个程序投的），所以第二个程序开始计划投4个币。。。
> 最后的结果就是，第一个程序投了5个，第二个程序投了4个，加起来一共9个。
> 
> ### 我是万万没想到，我写个单个用户使用的工具类软件，你竟然给我测出了高并发的Bug哈哈哈哈哈**
> 目前正常使用不会出现这种bug的，可以放心先用着。
> 
> 具体怎么解决（或者说需不需要解决）这种因为多开软件而引起的bug，后面我再考虑下。
> 解决也简单，就是再每次投币前都调接口查下今日已投币个数，但这样做同时也就会多调好几次接口，有取有舍吧，毕竟这个程序的初衷就是单纯的给一个人一天用一次而已。
> 
> 感谢反馈，朋友你太厉害了，你才是大佬，不做测试工程师是测试界的一大损失！

还好你参考我项目的时候我已经换了新的投币任务状态api （ https://www.bilibili.com/plus/account/exp.php），通过http://api.bilibili.com/x/member/web/exp/reward 获取的每日任务状态，投币获得的经验偶尔会返回一个0，这也会导致投币多投。

**Comment by happy888888** [comment]
> 自动投了9个币，设置里是默认的5个币，是出bug了

建议用`https://api.bilibili.com/x/web-interface/coin/today/exp`查询硬币，`https://www.bilibili.com/plus/account/exp.php`这个接口都不知道出处，而且尽量用同一个域名下的接口利于底层复用http连接

**Comment by RayWangQvQ** [comment]
> > 自动投了9个币，设置里是默认的5个币，是出bug了
> 
> 建议用`https://api.bilibili.com/x/web-interface/coin/today/exp`查询硬币，`https://www.bilibili.com/plus/account/exp.php`这个接口都不知道出处，而且尽量用同一个域名下的接口利于底层复用http连接

棒啊！改天我试下。

**Comment by antsman9** [comment]
https://www.52pojie.cn/?fromuser=antsman
可以试试？

**Comment by RayWangQvQ** [comment]
> https://www.52pojie.cn/?fromuser=antsman
> 可以试试？

@antsman9  ？？？

**Comment by happy888888** [comment]
> > https://www.52pojie.cn/?fromuser=antsman
> > 可以试试？
> 
> @antsman9 ？？？

这是它的推广链接，双11当天可以通过推广链接注册

**Comment by LHFA** [comment]
52

**Comment by antsman9** [comment]
> > > https://www.52pojie.cn/?fromuser=antsman
> > > 可以试试？
> > 
> > 
> > @antsman9 ？？？
> 
> 这是它的推广链接，双11当天可以通过推广链接注册

你的这个它 ，让我好尴尬~

**Comment by jiayaoO3O** [comment]
dotnet 5 出来了, 有没有升级上去的打算

**Comment by lhyUnited** [comment]
github trending来的
![screenshot](https://static.tomluvjerry.cn/files/lhyUnited/f3b438eeb1017d06923d81bc5ce70312.png)

**Comment by Mmx233** [comment]
telegram频道推荐来的

**Comment by LHFA** [comment]
吾爱破解过来的...为什么抄送了我一份 -.-



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mmx"<notifications@github.com&gt;; 
发送时间: 2020年11月15日(星期天) 下午4:51
收件人: "RayWangQvQ/BiliBiliTool"<BiliBiliTool@noreply.github.com&gt;; 
抄送: "1234"<274618350@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [RayWangQvQ/BiliBiliTool] 我是作者，进来的朋友谁能来告诉我下，你们都是从哪里过来的？ (#8)





 
telegram频道推荐来的

**Comment by TinQlo** [comment]
GitHub每日推荐（？
follow了好多聚聚，他们有star你的裤子，然后我就来啦qwq
