### ISSUE TITLE
一点小问题和建议

### ISSUE THREAD

**Issue by wangmanv2** [RayWangQvQ/BiliBiliTool#9]
有些小问题的样子 OTHERCONFIGS 的配置中appsettings.json每个参数不能直接复制对应参数名来修改么？
还有Secrets的[UserId][BiliJct]值在README.md内[1.1.第一步：获取自己的Cookie](https://github.com/RayWangQvQ/BiliBiliTool#11%E7%AC%AC%E4%B8%80%E6%AD%A5%E8%8E%B7%E5%8F%96%E8%87%AA%E5%B7%B1%E7%9A%84cookie)中BiliJct是有下划线的BILI_JCT；DEDEUSERID是USERID，有点反直觉。
还有【每月领取大会员漫画权益】目标领取日期为1号，今天是8号，跳过领取任务，只有在特定日子才领取么？那这个月1号过去了，现在不会自动领取漫画权益么？能否再加上一点判断？超过目标领取日期但是仍未领取就自动领取呢？ 
ps:能否加入自动领取小心心和自动送准备过期直播礼物的功能。

**Comment by RayWangQvQ** [comment]
## 1
问题：`OTHERCONFIGS 的配置中appsettings.json每个参数不能直接复制对应参数名来修改么？`
除了微信推送的key，当前其他都是用的配置文件中的二级key。你这里问的，我没理解错的话，应该是问“微信推送的配置key为什么和配置文件中的不一样”。
微信推送的key下个版本会考虑统一（考虑将配置文件的二级Key名称改掉）
## 2
问题： `Secrets的[UserId][BiliJct]值在README.md内1.1.第一步：获取自己的Cookie中BiliJct是有下划线的BILI_JCT；DEDEUSERID是USERID，有点反直觉。`
这个纯粹是命名风格的原因，C#没有用下划线连接两个单词的习惯，暂时不会考虑将Secret Key与实际Cookie Key统一。之前可能是图片经常挂的原因，导致有朋友配错了。现在已经有朋友提交了PR，在README里用文字重点提示了Secrets和Cookie的对应关系，应该能避免大部分朋友配置错误了。
## 3
问题：`每月领取大会员漫画权益】目标领取日期为1号，今天是8号，跳过领取任务，只有在特定日子才领取么？那这个月1号过去了，现在不会自动领取漫画权益么？能否再加上一点判断？超过目标领取日期但是仍未领取就自动领取呢？`
不是的，每月自动领取会员权益的日期和每月为自己充电的日期，都是可以配置的。如果错过了1号，建议在OTHERCONFIGS里配成今天运行一下就行了。
你说的超过领取日期自动领取，应该是指月底最后一天判断一下，没有领取就自动领取。这个之前没有考虑到，后面的版本会考虑加上，感谢反馈！

**Comment by RayWangQvQ** [comment]
## 4
问题：`能否加入自动领取小心心和自动送准备过期直播礼物的功能。`
只要是功能开通过调用接口实现，并且可以抓取到接口，然后接口可以通过Cookie认证成功，理论上就是有可能实现的。
但是最近个人比较忙，添加新功能的计划可能要等到半个月之后了。
代码都是开源的，如果有使用.NET Core开发的朋友，又刚好感兴趣，也欢迎前来为这个功能PR贡献自己的代码啦～～

**Comment by wangmanv2** [comment]
感谢作者的回复，第3点可能我描述不够清晰。

我想说的是对于`每月领取大会员漫画权益`这个功能比如我设定了1号，但是如果由于某些原因当月1号的时候程序没有运行起来，那么当之后程序恢复运行的时候，它就不会去领取权益。

我想能否请作者加一个判断就是如果当时的时间已经超过设定时间但是却没有领取漫画权益的时候自动领取。

（PS：这个超过目标领取日期并不是指月底最后一天，而是指超过设定领取的日期。）

**Comment by RayWangQvQ** [comment]
> 感谢作者的回复，第3点可能我描述不够清晰。
> 
> 我想说的是对于`每月领取大会员漫画权益`这个功能比如我设定了1号，但是如果由于某些原因当月1号的时候程序没有运行起来，那么当之后程序恢复运行的时候，它就不会去领取权益。
> 
> 我想能否请作者加一个判断就是如果当时的时间已经超过设定时间但是却没有领取漫画权益的时候自动领取。
> 
> （PS：这个超过目标领取日期并不是指月底最后一天，而是指超过设定领取的日期。）

嗯了解了，实现这个需求，需要一个“获取当前是否已领取大会员权益”的B站Api。有时间我去找找看，感谢反馈。

**Comment by hjkl950217** [comment]
“这个纯粹是命名风格的原因，C#没有用下划线连接两个单词的习惯” 这个确实是的，但也不是说不能这样做。
我之前有一段时间写代码就是会写比较长的名字(商业业务项目，逻辑深)，如"AaaBBBCcc_Ddd".后面开始考虑一些设计上的事，等于把这些分字分散到不同的类中去了。

但常量写成下面这种也不是不行:
```
/// <summary>
///  XXXXX
/// </summary>
public const string ABCD_EF_G=""；
```

习惯原因吧，只要项目内风格统一、设计合理就行
